### ISSUE TITLE
chrome app does not exit on failure

### ISSUE THREAD

**Issue by rupeshmore** [oblador/loki#1]
Kudos for building a cool visual regression suite. I love it. It's fast with minimal setup and just works.

While testing the tool using the existing react example, I discovered whenever the visual test failed the chrome app did not close.

Machine Specs:
Macbook - OSX - Yosemite. 
Chrome Browser - Version 60.0.3112.78 (Official Build) (64-bit).

**Comment by oblador** [comment]
Hey! This should be fixed in 0.5.3, try it out! Have bumped the examples too :-)

**Comment by rupeshmore** [comment]
Fixed in 0.5.3. Closing the issue.
