### ISSUE TITLE
Detect loki tests from the app

### ISSUE THREAD

**Issue by vvscode** [oblador/loki#109]
Is it possible or not? (Or feature request, if not) - add class / detect by user-agent and so on.

What for it might be used - to ignore/disable particular areas on screen shot ( set opacity for example )

**Comment by techeverri** [comment]
> What for it might be used - to ignore/disable particular areas on screen shot ( set opacity for example )

Elements with the following properties would be identified not visible

https://github.com/oblador/loki/blob/f8954830b86b1308c45e607046b9f1c3cef455bf/src/targets/chrome/get-selector-box-size.js#L15-L25

**Comment by vvscode** [comment]
I realize it. But currently, I have components with dynamic content. So it should be out of screenshot. Only for tests.

in `gemini` for example, I could set ignore selectors. In loki I see no such options. So I want ignore valuable elements, but only for tests

Is it possible?

**Comment by vvscode** [comment]
https://gemini-testing.github.io/doc/tests.html 

```ignoreElements('.selector1', {every: '.selector2'}, ...) — elements, matching specified selectors will be ignored when comparing images.

.selector1 — Ignore only the first matched element.
{every: '.selector2'} — Ignore all matched elements.```

**Comment by vvscode** [comment]
What do I mean - for example at https://github.com/oblador/loki/blob/02301c9548c68ca3e60c5033ce23c1d19d341d3d/src/targets/chrome/create-chrome-target.js#L246 add `loki-tests` attr to `html` tag so in my styles I could write

```css
/* loki specific styles */
[loki-tests] .map {
    opacity: 0;
}
```

**Comment by vvscode** [comment]
I'm ready try implement it by myself if the team is ok about this suggestion

**Comment by oblador** [comment]
It's actually part of the roadmap :-) https://github.com/oblador/loki/projects/1#card-5208258

Would love some help if you need it soon.

**Comment by vvscode** [comment]
@vvscode @oblador  it would be nice to see some contributors guide. Not obvious how to test changes and so on - I spent 3 hours for small update

**Comment by vvscode** [comment]
and this one might be closed, I guess =)
