### ISSUE TITLE
Different results in different environments

### ISSUE THREAD

**Issue by vvscode** [oblador/loki#112]
I'm using gitlabCI as CI server. 

Situation is next: locally all tests pass, but on gitlabci - they fail. Diff in attachment. Everything works in Docker so I'm confused. Any ideas?

```js
  "loki": {
    "chromeSelector": ".uil-story-wrapper > *",
    "preset": "Retina Macbook Pro 15",
    "skipStories": "(Row|Col|Map|Calendar|Pagination|ContactCard|TextArea)$",
    "configurations": {
      "chrome.laptop": {
        "target": "chrome.docker",
        "width": 1366,
        "height": 768,
        "deviceScaleFactor": 1,
        "mobile": false,
        "fitWindow": false
      }
    }
  }
```
![chrome_laptop_legacy_legacycheckbox](https://user-images.githubusercontent.com/6904368/47615163-20e39b80-dac5-11e8-8d87-8e7aba546424.png)

**Comment by maniator** [comment]
I have this same issue

![image](https://user-images.githubusercontent.com/539579/53838935-434e5f80-3f64-11e9-946d-31aac3a63dd7.png)


I don't really see the difference that the first image sees -- ran in circle ci

**Comment by vvscode** [comment]
@maniator  I solved an issue for myself with next hack:
` .storybook/preview-head.html` :


```html
<script>
(function() {
  var isLocalFileSession = !window.location.href.startsWith('http');
  if (isLocalFileSession) {
    console.log('[UI-LIB: WARNING] Please keep in mind, that some animations and styles are patched. Check the file `preview-head.html');
    var style = document.createElement('style');
    // https://dev.webonomic.nl/how-to-disable-css-transforms-transistions-and-animations
    style.innerHTML = `
    *, :before, :after {
      animation-duration: 0s !important;
    }
    /*
     ESRI relies on external resources, 
     so it might behave upredictable depends on environment
    */
    .esri-view-root {
      opacity: 0;
    }
    `;
    window.document.head.appendChild(style);
  }
})();
</script>
```

**Comment by maniator** [comment]
@vvscode My issue mainly seems to be with svg rendering locally vs on CI.

That is where all the diffs are -- in SVGs

**Comment by vvscode** [comment]
@maniator following hack above - you can just hide svg elements from capturing

add `opacity: 0` for failed elements (see `.esr-view-root` - the same example )

**Comment by maniator** [comment]
> @maniator following hack above - you can just hide svg elements from capturing
> 
> add `opacity: 0` for failed elements (see `.esr-view-root` - the same example )

@vvscode 	but these are svgs loaded with css throughout storybook, how do we focus on all of them?

**Comment by oblador** [comment]
@vvscode I'm trying to support gitlab in a nice way, how did you solve it?

**Comment by vvscode** [comment]
> @vvscode but these are svgs loaded with css throughout storybook, how do we focus on all of them?

Didn't get. Hack above allows you to ignore some elements from screenshots. In my case, it was a map. In your case, it might be some other elements. I know - this is a workaround, but that's all I found



> @vvscode I'm trying to support gitlab in a nice way, how did you solve it?

Looks like I don't understand ((
