### ISSUE TITLE
React-Native support for Storybook 4.0?

### ISSUE THREAD

**Issue by holtat** [oblador/loki#121]
First, I was able to integrate Loki with the React Storybook and really appreciate the features including dockerized chrome support!

I then went to try out the React Native version, but can't seem to connect to the Storybook server:

```
loki test v0.14.1
  ✔ Chrome (docker)
  ❯ iOS Simulator
    ✖ Start
      → Failed preparing for loki. Make sure the app is configured and running in storybook mode.
      Fetch list of stories
      Test ios
      Stop
Failed preparing for loki. Make sure the app is configured and running in storybook mode.
Error: Failed preparing for loki. Make sure the app is configured and running in storybook mode.
    at Object.start (/Users/holtan/Repos/storybook-examples/storybook-react-native/node_modules/loki/src/targets/native/create-websocket-
target.js:98:13)
    at <anonymous>
```

Versions:
```
"loki": "0.14.1",
"react-native": "0.57.8",
"@storybook/react-native": "4.1.2",
```

I've tried to use both the old and new way of running RN Storybook 4.0 detailed here: https://medium.com/storybookjs/whats-new-in-storybook-4-0-react-native-741c7f481bbb

I started up the old Storybook RN web server running on port 7007, but still couldn't connect.

Your [RN example](https://github.com/oblador/loki/tree/master/examples/react-native) uses Storybook 3.x. I'd be happy to submit an MR if you think it should be working with 4.0.

Thanks!

**Comment by oblador** [comment]
Hey! Happy you enjoy it so far :-) Does it work when running storybook in regular fashion via the browser?

**Comment by holtat** [comment]
Thanks for the quick response!

I ran

```
node ./node_modules/@storybook/react-native/dist/bin/storybook-start.js
```

to start the react-native storybook server which successfully built and ran on port 7007.

I then ran

```
npm start -- --projectRoot .storybook/mobile
```

to start the RN packager with my Storybook entry point.

```
// .storybook/mobile/index.js
import { name as appName } from '../../app.json';
import { AppRegistry } from 'react-native';
import { getStorybookUI, configure } from '@storybook/react-native';

configure(() => {
    require('../../src/components/button/button.story.js');
}, module);

const StorybookUI = getStorybookUI();

AppRegistry.registerComponent(appName, () => StorybookUI);
```

I opened the app and see RN Storybook running on the iOS simulator. I can open localhost:7007 and control what is shown on the simulator.

![screen shot 2018-12-20 at 9 03 12 am](https://user-images.githubusercontent.com/4681530/50289206-23fc6780-0436-11e9-8cb1-d362e46e9a4c.png)

**Comment by oblador** [comment]
Looks like you didn’t add the loki registration import, have a look at the example how (may need to add it first of all imports).
