### ISSUE TITLE
0.6.2 works on CI but fail in my machine

### ISSUE THREAD

**Issue by felquis** [oblador/loki#13]
0.6.2 works fine on CI, but on my machine I can only test and update reference images with v0.6.2

0.6.2 breaks with:
```txt
loki test v0.6.2
 ❯ Chrome (docker)
   ✖ Start
     → Timeout
     Fetch list of stories
     Test chrome.palm
     Stop
Timeout
Error: Timeout
    at Timeout._onTimeout (/home/felquis/pagarme/pilot/webapp/node_modules/wait-on/lib/wait-on.js:91:10)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
error Command failed with exit code 1.
```

uname -a 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
node -v 8.1.2

**Comment by oblador** [comment]
Are you using static files or dev server?

**Comment by felquis** [comment]
dev server

**Comment by oblador** [comment]
Can you try with static files as suggested in the docs?

**Comment by oblador** [comment]
And how do you start the dev server?

**Comment by oblador** [comment]
Ooh, it broke locally. Misread the title. Can you try passing `--chromeFlags='--headless --disable-gpu --hide-scrollbars --cap-add=SYS_ADMIN'`?

**Comment by felquis** [comment]
I'm using
```
"shooting-stars": "wait-on http://0.0.0.0:6006 && loki --requireReference --skipStories /^Progress/ --chromeFlags='--headless --disable-gpu --hide-scrollbars --cap-add=SYS_ADMIN'",
```

But yet throwing the same error
```txt
loki test v0.6.2
 ❯ Chrome (docker)
   ✖ Start
     → Timeout
     Fetch list of stories
     Test chrome.palm
     Stop
Timeout
Error: Timeout
    at Timeout._onTimeout (/home/felquis/pagarme/pilot/webapp/node_modules/wait-on/lib/wait-on.js:91:10)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

**Comment by oblador** [comment]
Hmm, are you using a proxy/vpn? Have had problems with that when using docker. Also, any luck with static files?

**Comment by felquis** [comment]
It works with 0.6.1 but doesn't using 0.6.2

**Comment by felquis** [comment]
These commits may help you debug it https://github.com/pagarme/pilot/pull/274#issuecomment-333410875
