### ISSUE TITLE
yarn loki init error

### ISSUE THREAD

**Issue by ruxiang05** [oblador/loki#16]
I'm receiving a 'Cannot read property 'react-native' of undefined' when trying to initialise. My project is in React.

**Comment by oblador** [comment]
Hi, do you use a `package.json` with a `dependencies` key defined?

**Comment by ruxiang05** [comment]
Yes

**Comment by Gongreg** [comment]
I would suggest adding somewhere in readme manual installation. For me init didn't work too, so I looked into what it does to make it work.

**Comment by cshell7** [comment]
I am also having this bug. I'm using loki v0.8.0, node 8.4.0.

**Comment by cshell7** [comment]
Looks like `hasReactNativeDependency()` in `src/config/project-package.js` is always returning true. As a quick temporary fix so I could keep working I hardcoded it to return false. Works for now but a better solution is still needed.

**Comment by cshell7** [comment]
Correction, it wasn't returning true, just blew up cause dependencies weren't defined in package.json. Suggested fix for this https://github.com/oblador/loki/issues/16

**Comment by nuc** [comment]
Should be fixed now there: https://github.com/oblador/loki/pull/49
