### ISSUE TITLE
Lighthouse/chrome-launcher/random-port is not available in the lighthouse@2.5.0

### ISSUE THREAD

**Issue by alexeybondarenko** [oblador/loki#17]
Hey. 

I installed loki with npm and have found that it's not starting. The error is about that Lighthouse/chrome-launcher/random-port is unavailable.

I could try to migrate to 2.5.0 if it's needed.

**Comment by Gongreg** [comment]
The issue is that this module is required globally. Even though I want to use loki for RN, I still need to have these dependencies or I get an error.

**Comment by oblador** [comment]
Hi, this should be fixed in 0.6.4!

**Comment by alexeybondarenko** [comment]
@oblador thanks!

**Comment by Gongreg** [comment]
@oblador, hero! :D
