### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by SQReder** [oblador/loki#182]
We use Typescript for stories and so `.skipLoki()` and `asyncLoki()` is not available

**Comment by ManAnRuck** [comment]
typescript support would be very interesting

**Comment by techeverri** [comment]
The `lokiSkip` Storybook decorator is deprecated (via #228) along with support for Storybook prior to v5 since Loki [v0.23.0](https://github.com/oblador/loki/releases/tag/v0.23.0)

So apart from the deprecated decorator above, `lokiAsync`, and `lokiAsyncSkip`.
I wonder What else could be typed using TypeScript?

**Comment by oblador** [comment]
@techeverri IMHO, we should include d.ts files for the packages consumed directly, being `@loki/is-loki-running` and `@loki/create-async-callback`. I'd regard the `.skipLoki()` and `.asyncLoki()` as obsolete/to be deprecated.

**Comment by techeverri** [comment]
They use a very interesting approach for distributing the types for the packages the `@sentry/` monorepo
🔗 https://github.com/getsentry/sentry-javascript/tree/master/packages/types

There is a package in the monorepo called `@sentry/types` that consists only of `*.ts` files with the types
🔗 https://www.npmjs.com/package/@sentry/types

Compiling these files using TypeScript generates a bunch of `*.d.ts` files
🔗 https://unpkg.com/browse/@sentry/types@5.29.0/dist/

Using the `types` property in the `package.json`
```json
"types": "dist/index.d.ts",
```
🔗 https://github.com/getsentry/sentry-javascript/blob/928e96a6eee041f95e0a3c0da6bcc6f9ca2e885b/packages/types/package.json#L14

The files are then packed/exported and published (standalone)
🔗 https://www.npmjs.com/package/@sentry/types

The package can be consumed as follows (both within the monorepo and externally)
```js
import { Event, EventHint, Options, Severity } from '@sentry/types';
```
🔗 https://github.com/getsentry/sentry-javascript/blob/928e96a6eee041f95e0a3c0da6bcc6f9ca2e885b/packages/browser/src/eventbuilder.ts#L1


What do you think? @oblador

**Comment by AntonNiklasson** [comment]
It looks like the exports from both `create-async-callback` and `is-loki-running` are straight forward. Without any background on the repo setup here, just having an `index.d.ts` in each package should be good enough, no?

I'd be happy to PR it if it sounds like a good idea.

**Comment by techeverri** [comment]
Go for it @AntonNiklasson 👍 

> just having an `index.d.ts` in each package should be good enough, no?

I hope so 🤞 
_We'll have to test before merging_

**Comment by AntonNiklasson** [comment]
Any chance we could have this released, @techeverri? 🙏
