### ISSUE TITLE
Error trying run Loki on CircleCI

### ISSUE THREAD

**Issue by raryson** [oblador/loki#183]
Hello folks, we are trying run Loki in CircleCI and we are receiving this error:
```
loki test v0.18.1
[17:53:06] Chrome (docker) [started]
[17:53:06] Prepare environment [started]
[17:53:12] Prepare environment [completed]
[17:53:12] Start [started]
[17:53:19] Start [failed]
[17:53:19] → Chrome failed to start with error "[1129/175314.012062:WARNING:resource_bundle.cc(366)] locale_file_path.empty() for locale 
[1129/175314.022201:WARNING:resource_bundle.cc(366)] locale_file_path.empty() for locale 
DevTools listening on ws://0.0.0.0:37689/devtools/browser/298ceb3f-62ad-48c3-90c6-18d081177435"
[17:53:19] Chrome (docker) [failed]
[17:53:19] → Chrome failed to start with error "[1129/175314.012062:WARNING:resource_bundle.cc(366)] locale_file_path.empty() for locale 
[1129/175314.022201:WARNING:resource_bundle.cc(366)] locale_file_path.empty() for locale 
DevTools listening on ws://0.0.0.0:37689/devtools/browser/298ceb3f-62ad-48c3-90c6-18d081177435"
Chrome failed to start with error "[1129/175314.012062:WARNING:resource_bundle.cc(366)] locale_file_path.empty() for locale 
[1129/175314.022201:WARNING:resource_bundle.cc(366)] locale_file_path.empty() for locale 
DevTools listening on ws://0.0.0.0:37689/devtools/browser/298ceb3f-62ad-48c3-90c6-18d081177435"
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

We are trying run with this CircleCI config:
```
version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          yarn
          yarn test:visual
```

Our run command is this: 
```
"test:visual": "npm run build-storybook -s /pubic && loki --reactUri \"file:./storybook-static\" --chromeFlags=\"--no-sandbox --headless --disable-gpu --hide-scrollbars\"",
```

**Comment by farisk** [comment]
Also experienced the same issue. For now I target chrome.app rather than chrome.docker and use the circleci/node:lts-browser image. You will have to also generate the loki reference images in the same image though to get accurate results.

**Comment by Kristof-Mattei** [comment]
@farisk the other option is to not run it with `docker`, but on a `machine` on which you do `setup_remote_docker`. 

It does come with 2 caveats:
* It is significantly slower 
* We get intermittent socket resets that we can't seem to debug

But all in all we now run a separate job that does the stories on a `machine`, the rest runs on `docker`. in parallel.

**Comment by rwieruch** [comment]
@raryson any chance that you got this running with `chrome.docker`? If it helps, I laid out my setup over here https://github.com/oblador/loki/issues/204 but I run into the same error.

**Comment by AvnerCohen** [comment]
In a team with more than one member, any visual testing that is not based on chrome.docker will make little sense. Snapshots are doomed to differ from one install to another, so getting this up and running on a CI seems to be an urgent need, I am totally not sure what am I missing in the setup.
I am too working circleCI, and running the simple docker in docker setup, with the added `setup_remote_docker` I am getting:

```
[test] $ yarn loki test --chromeDockerImage yukinying/chrome-headless-browser:82.0.4083.0
[test] $ /home/circleci/react-components/node_modules/.bin/loki test --chromeDockerImage yukinying/chrome-headless-browser:82.0.4083.0
[test] loki test v0.20.1
[test]PASS chrome.docker/PREPARE
[test]FAIL chrome.docker/START: Chrome failed to start with error "DevTools listening on ws://0.0.0.0:41309/devtools/browser/de2e2b67-12fe-4ffb-af84-eedda6bae09f"
[test]Some visual tests failed to run
```

This is latest chrome-headless-browser and from what I see the chrome is actually up and running and everything is fine there. what I suspect is that this is simply a bug in the docker-in-docker setup around the wait-on command https://github.com/oblador/loki/blob/ac8d54b36cabedc8a4a4f9463efd111f9945adc8/packages/target-chrome-docker/src/create-chrome-docker-target.js#L26

**Comment by AvnerCohen** [comment]
This is the info from within the circle ci container.

docker is up and logs are all clean:
```
circleci@ddc16b45cf39:~/react-components$ docker logs --tail 100  7f762a280db5

DevTools listening on ws://0.0.0.0:35671/devtools/browser/eba9dfb5-e255-44d4-aed0-a579b513ba46
circleci@ddc16b45cf39:~/react-components$ docker ps
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                      NAMES
7f762a280db5        yukinying/chrome-headless-browser:82.0.4083.0   "/usr/bin/dumb-init …"   4 minutes ago       Up 4 minutes        0.0.0.0:35671->35671/tcp   competent_sinoussi
```

**Comment by AvnerCohen** [comment]
My conclusion at this point is that this is a CircleCi issue, opened a case there, will update.

**Comment by Kristof-Mattei** [comment]
https://github.com/oblador/loki/pull/218

I managed to drop down my error rate to 0 with this one ^

**Comment by rwieruch** [comment]
Anyone of you using `chrome.docker` @AvnerCohen @Kristof-Mattei ?

**Comment by AvnerCohen** [comment]
@rwieruch Yes.
As shown in the console logs I posted, this is a docker in docker case.
Locally (osx):
`$> wait-on tcp:35671`
will work just fine and won't block, on the circleci, it is blocked and so testing never starts (it's not about flakiness, "[test]FAIL chrome.docker/START: Chrome failed to start with error").
I am guessing it is some specific setup of port control inside the circleci docker, I have opened a case fro circleci on this, hoping for some resolution from their end.

**Comment by rwieruch** [comment]
@AvnerCohen I would be supper happy if you could share your Loki + Docker setup with us! I tried to get it working https://github.com/oblador/loki/issues/204 bu maybe I just overcomplicate things over there.

**Comment by AvnerCohen** [comment]
@rwieruch Here is a complete repro to show case this:
https://github.com/AvnerCohen/lok-dnd-repro
You can test locally:
`$> yarn install && build-storybook -c .storybook && yarn test:visual:ci`
and it will pass.

You can see that the circle ci build is failing with:
https://app.circleci.com/pipelines/github/AvnerCohen/lok-dnd-repro/7/workflows/c383ad89-ffd2-4792-8299-55455fa64a0c/jobs/7

**Comment by rwieruch** [comment]
Thanks!

I still get the same error as in my other issue on MacOS:

```
loki test v0.20.1
 FAIL  chrome.docker
       Starting
       Chrome failed to start with errors "", "DevTools listening on ws://0.0.0.0:52356/de
vtools/browser/efe5590c-b393-4b9b-bd41-b7df8c002978"
Some visual tests failed to run
```

Everything works when I do `chrome.app`. 

In case I get past this eventually, I will tackle the whole thing with CI as well.

**Comment by AvnerCohen** [comment]
@rwieruch This is exactly the point of this repro code.
It's not working.

with chrome.app, you are basically running the headless browser in the circleci docker.
with chrome.docker, you are running a docker inside the circle docker, hence a docker in a docker.
This mode does not work for some reason in the circleci setup.

**Comment by AvnerCohen** [comment]
btw if relevant to anyone, works off the bat with TravisCI - https://travis-ci.org/github/AvnerCohen/lok-dnd-repro/builds/663473334

**Comment by rwieruch** [comment]
> @rwieruch This is exactly the point of this repro code.
> It's not working.
> 
> with chrome.app, you are basically running the headless browser in the circleci docker.
> with chrome.docker, you are running a docker inside the circle docker, hence a docker in a docker.
> This mode does not work for some reason in the circleci setup.

Thanks again. But just in case my text wasn't clear:  `yarn test:visual:ci` doesn't work for me locally either. I get this error instead.

> Thanks!
> 
> I still get the same error as in my other issue on MacOS:
> 
> ```
> loki test v0.20.1
>  FAIL  chrome.docker
>        Starting
>        Chrome failed to start with errors "", "DevTools listening on ws://0.0.0.0:52356/de
> vtools/browser/efe5590c-b393-4b9b-bd41-b7df8c002978"
> Some visual tests failed to run
> ```
> 
> Everything works when I do `chrome.app`.
> 
> In case I get past this eventually, I will tackle the whole thing with CI as well.

It seems like for you it works at least on your local machine.

**Comment by AvnerCohen** [comment]
For the very specific case of CircleCI there seem to be a solution, moving to [machine executor](https://circleci.com/docs/2.0/executor-types/#using-machine).
The exect commit that solved it on my test repo - https://github.com/AvnerCohen/lok-dnd-repro/commit/9999c29d6305395db55432a1c4eb3b880c421670
This is admittedly not the cleanest option, but it totally does the job :)

**Comment by rwieruch** [comment]
Congrats that you did it @AvnerCohen 🎉 Thanks for sharing 👍

**Comment by raryson** [comment]
Thanks @AvnerCohen i will test

**Comment by donaldpipowitch** [comment]
Anyone knows a similar fix for GitLab?

```
 FAIL chrome.docker/START: Chrome failed to start with errors "[0423/042122.560908:WARNING:resource_bundle.cc(366)] locale_file_path.empty() for locale", "[0423/042122.587247:WARNING:resource_bundle.cc(366)] locale_file_path.empty() for locale", "", "DevTools listening on ws://0.0.0.0:44295/devtools/browser/61c98ef7-f021-4ff4-a50b-3a5884033c03", "[0423/042122.604941:ERROR:address_tracker_linux.cc(174)] Could not bind NETLINK socket: Address already in use (98)"
```

**Comment by mat-przybylowski** [comment]
@AvnerCohen Thanks so much for sharing your circleCI machine executor setup! 

I wish it were documented in the loki documentation.
