### ISSUE TITLE
Unable to switch between stories

### ISSUE THREAD

**Issue by fmnxl** [oblador/loki#186]
Padding `{ kind, story }` to `setCurrentStory` is now deprecated. On react-native, it's no longer supported.

I've made a hacky quick fix (https://github.com/oblador/loki/pull/187), but I'm willing to submit a proper fix if anyone has a better idea how to fix the issue

**Comment by wilau2** [comment]
@oblador I'm experiencing the same issue as @purelysloth and wanted to test out Loki out of the `master` branch since #187 have been merged. Do you have any instructions on how to test out of the master branch in another project?

**Comment by kolohelios** [comment]
@wilau2 and for anyone else that comes across this issue prior to a new release dropping. In cases like this, I've worked around package issues by using [patch-package](https://www.npmjs.com/package/patch-package). It's extremely helpful and once patches are committed, you can safely share patched packages with the rest of your team.

**Comment by oblador** [comment]
This is now fixed in [0.19.0](https://github.com/oblador/loki/releases/tag/v0.19.0)
