### ISSUE TITLE
[Suggestion] Notify if there is no reference for a story

### ISSUE THREAD

**Issue by Gongreg** [oblador/loki#19]
Right now when story doesn't have reference, the test simply pass. A warning could be really helpful  so people wouldn't forget to add new references for stories.

**Comment by oblador** [comment]
Hi, there's the `requireReference` flag/config to fail tests without reference. My intention is to make this default when running in CI and automatically update the reference for new tests.

**Comment by Gongreg** [comment]
Oh, missed that one :) But I think it could make sense to see only the warning, since your current tests don't have any errors. Just my two cents :)
