### ISSUE TITLE
[Question] All reference images in React Native example are the same

### ISSUE THREAD

**Issue by kantorm** [oblador/loki#199]
I wonder if that is alright that all reference images in React Native example are the same. I thought that loki should make a screenshot of every storybook, not just one. Is this a bug or I just misunderstood how it should work?

**Comment by a-ster** [comment]
Got the same experience. I can't find any documentation how can Loki navigate to each of the component in the storybook and take a screenshot of the Preview. Please help!

**Comment by a-ster** [comment]
> Got the same experience (edited my comment to provide more details).
> 
> I tried the react-native example in the loki project using the following steps:
> 
> 1. Navigate to `./loki/examples/react-native`
> 2. Run `yarn` to install packages
> 3. Run `yarn storybook`
> 4. Run `yarn ios`
> 5. In the storybook, navigate to `Button with text` story
> 6. Run `yarn loki update`
> 7. In the storybook, navigate to `Welcome to storybook` story
> 8. Run `yarn loki test`
> 9. Check generated screenshots
> 
> **Expected result:** Screenshots should be generated for each individual story matching the component.
> **Actual result:** Though the filenames of the generated screenshots are correct, the screenshots generated is for current active story in the simulator.
> 
> I have attached the generated screenshots for Steps 6 and 8.
> [reference.zip](https://github.com/oblador/loki/files/4150330/reference.zip)
> [current.zip](https://github.com/oblador/loki/files/4150331/current.zip)

Found that this is actually related to https://github.com/oblador/loki/issues/186. I have applied the fix locally and it was able to navigate to each story.

**Comment by kantorm** [comment]
@oblador If #186 was a fix for that when should we expect a release that includes it?

**Comment by oblador** [comment]
Hey, the fix is now out in [0.19.0](https://github.com/oblador/loki/releases/tag/v0.19.0).
