### ISSUE TITLE
Failing to get storybook static image w/ crossOrigin attribute

### ISSUE THREAD

**Issue by junkboy0315** [oblador/loki#201]
Hello folks!

I need to get the image by specifying the crossorigin attribute.

```jsx
<img
  crossOrigin="anonymous"
  src="/some-img-in-the-public-folder-of-storybook.png"
/>
```

In this case, the command below will succeed.

```sh
# run storybook independently
yarn storybook

# after that, run loki test in another shell
yarn loki test
```

but the command below will fail.

```sh
# build static site and capture it
yarn build-storybook && yarn loki --reactUri file:./storybook-static test
```

<img width="662" alt="スクリーンショット 2020-01-30 14 55 19" src="https://user-images.githubusercontent.com/10986861/73424974-a2367780-4373-11ea-8c49-ff93abfebdfa.png">

I think this is related to the CORS things because the problem disappears completely if I change the src to another host that allows CORS as follows.

```jsx
<img crossOrigin="anonymous" src="https://i.imgur.com/oxh6EDe.jpg" />
```

Considering the problem is only happening when loki is serving(?) a static site,
should I tell loki to allow CORS? How can I do that?

**Comment by oblador** [comment]
Hi,

Try passing the `--disable-web-security` flag in the `chromeFlags` option while also adding in the default ones mentioned in the docs.

**Comment by junkboy0315** [comment]
Hi! @oblador
Specifing the option and switching to the latest chrome solved the problem.
Thanks!

```sh
yarn loki \
  --chromeDockerImage yukinying/chrome-headless-browser:79.0.3945.16 \
  --chromeFlags \"--headless --disable-gpu --hide-scrollbars --disable-web-security \" \
  --requireReference \
  --reactUri file:./storybook-static
```

**Comment by junkboy0315** [comment]
sorry, actually upgrading chrome is not required.
following is just enough. thanks.

```sh
 yarn loki \
   --chromeFlags=\"--headless --disable-gpu --hide-scrollbars --disable-web-security\"
   --reactUri file:./storybook-static \
   --requireReference \
   test
```
