### ISSUE TITLE
Don't restrict configuration only by package.json

### ISSUE THREAD

**Issue by kirilldronkin** [oblador/loki#203]
Hi, thank you for your work. It would be cool to let those who prefer not to configure anything in package.json (for me, as example) to use separate files for Loki configuration, e.g. `.lokirc`. Also with appropriate cli option this approach allows to vary configuration for different environments or projects inside one repository. Fortunately there are libraries that ease implementation of config resolving, e.g.  [cosmiconfig](https://github.com/davidtheclark/cosmiconfig). What do you think about it?

**Comment by oblador** [comment]
Released in [0.20.0](https://github.com/oblador/loki/releases/tag/v0.20.0)!
