### ISSUE TITLE
Loki fails when a third party integration fails

### ISSUE THREAD

**Issue by Geloloboy** [oblador/loki#206]
So as a background, out stories are connected to third party software like launchDarkly. Problem arises when we get connection errors to these software and we end up failing the whole thing.

It'll be good to have the option to ignore these errors altogether.

Sample error:
`https://app.launchdarkly.com/sdk/evalx/5d7ee19e68227207a7eed574/users/eyJhbm9ueW1vdXMiOnRydWUsImtleSI6ImE4YTM1MDUwLTUxZTQtMTFlYS05MmE1LThiMDJ9YzFhMjc5ZiJ9`

**Comment by oblador** [comment]
Hi, 

Latest version of loki has a new option called [fetchFailIgnore](https://loki.js.org/configuration.html#fetchfailignore) to handle these situations.
