### ISSUE TITLE
Loki file name comparison should not be dependent on the OS

### ISSUE THREAD

**Issue by Geloloboy** [oblador/loki#208]
It seems that Loki's file name comparison is dependent on the OS its running in. In Mac, its case insensitive, but in Linux, its case sensitive. This causes problems when you're working in Mac and then your CI is running in Linux. Local runs don't get the filename inconsistency while the Pipeline fails.

It should be consistent regardless of the OS.

**Comment by oblador** [comment]
Released in [0.20.0](https://github.com/oblador/loki/releases/tag/v0.20.0)!

**Comment by Geloloboy** [comment]
Thanks @oblador.

Unfortunately this doesn't entirely fix my issue:

1. The fileNameFormatter config doesn't seem to have an option to use the old naming convention and just transform it to lower case. Closest one I got was:
old: _chrome_all_Atoms_Add_Button_Clickable.png_
new: _chrome.all_Atoms|Add Button_Clickable.png_

2. Having a '/' in the name of the story causes another hierarchy level to appear (i.e. Items O/U)

**Comment by oblador** [comment]
You can do whatever you like with that string, such as replacing characters or run it through some slugify library.
