### ISSUE TITLE
Loki binary not being registered

### ISSUE THREAD

**Issue by aarongarciah** [oblador/loki#221]
Since `0.19.0`, Loki's binary fails to be registered. This is the output when installing Loki via `yarn global` using every version from `0.18.1` until `0.21.1`, see how yarn warns about the lack of binary being installed:

### Loki 0.18.1

<img width="378" alt="Screenshot 2020-03-13 at 08 10 31" src="https://user-images.githubusercontent.com/7225802/76599701-d1f5a500-6505-11ea-9831-beabfac7d0be.png">

### Loki 0.19.0

<img width="316" alt="Screenshot 2020-03-13 at 08 14 04" src="https://user-images.githubusercontent.com/7225802/76599704-d326d200-6505-11ea-8ac8-f24e8053eb7c.png">

### Loki 0.19.1

<img width="314" alt="Screenshot 2020-03-13 at 08 22 59" src="https://user-images.githubusercontent.com/7225802/76599705-d326d200-6505-11ea-8c16-72db67ddeffb.png">

### Loki 0.20.0

<img src="https://user-images.githubusercontent.com/7225802/76599696-d02be180-6505-11ea-827f-93b43d47f579.png" width="310" />

### Loki 0.20.1

<img width="312" alt="Screenshot 2020-03-13 at 08 11 00" src="https://user-images.githubusercontent.com/7225802/76599703-d28e3b80-6505-11ea-828d-70ef25076abf.png">

This is problematic when installing Loki in a Docker image and you want to use the binary command and it doesn't exist. You need to locate the binary path by hand to execute it.

Thanks for your hard work @oblador. Keep up the great work!

**Comment by oblador** [comment]
Fixed in [0.20.2](https://github.com/oblador/loki/releases/tag/v0.20.2].

**Comment by aarongarciah** [comment]
Thank you @oblador!
