### ISSUE TITLE
Upgrade minimum required Node.js version to an active LTS or current

### ISSUE THREAD

**Issue by techeverri** [oblador/loki#230]
### Context

According to the [docs](https://github.com/oblador/loki#prerequsites) and the [`package.json`](https://github.com/oblador/loki/blob/caa4742573e8f98cb79d08428809eddff1e4cbdb/package.json#L16), the minimum required version of Node.js for Loki  is 7.6 or higher

### Issue

Node.js 7.x was released [2016-10-25](https://nodejs.org/en/download/releases/#:~:text=Node.js%207.0.0) and end-of-life (last commit) happened [2017-07-11](https://github.com/nodejs/node/commits/v7.x)

Considering that Node.js 7.x is officially unsupported and that there is no point on supporting deprecated versions we could upgrade the minimum required version to an active TLS 
e.g. Node.js 10.x end-of-life will be 2021-04-30 (more info table and link below)

![image](https://user-images.githubusercontent.com/3720424/78345938-9eef8000-759e-11ea-86d3-2505df02eb27.png)
🔗 https://nodejs.org/en/about/releases/

**Comment by oblador** [comment]
I'm fine with bumping to 10 :-)

**Comment by oblador** [comment]
Or just removing the notice all-together.

**Comment by techeverri** [comment]
Sorry for the inactivity.
I had almost all the (untested) changes in a local branch but I lost that laptop 🙈 

This issue was more about to actually upgrade the project to an active LTS version of Node.js and not about the notice in the code 😅 

Let me know if it makes sense to re-open and I will try to update all the places to use the same version for both testing (during development) and running Loki itself.

**Comment by techeverri** [comment]
The Node.js version required to run the project can be found in the `.nvmrc` file https://github.com/oblador/loki/pull/353
