### ISSUE TITLE
Unable to get position of selector "#root > *

### ISSUE THREAD

**Issue by gsouf** [oblador/loki#245]
Hi,

When I run loki test then I get the following message for one and only one of my components:

```Failed with "Unable to get position of selector "#root > *". Review the `chromeSelector` option and make sure your story doesn't crash." after 4 tries```

This component performs some operations on mount, nothing crazy, just an async task, but should resolve immediatly in this env. So I  believe it might be related.
This component works perfectly well when I visit storybook in the browser.

I'm trying to understand why it fails. Does loki somehow modify the environment that could affect the js runtime and thus get my component to fail to render with loki? 

If so can I reproduce this environment in the browser, or have more details error logs?

Thanks

**Comment by oblador** [comment]
Can you post an example to reproduce the issue? Loki does some things to remove animations by patching `requestAnimationFrame` for example. You can try to disable that setting, but it could lead to flaky tests.

**Comment by gsouf** [comment]
@oblador do you have a dummy repo example that we can use to easily provide replicate samples?

**Comment by gsouf** [comment]
@oblador disregard my previous message.

I couldnt reproduce my exact issue because in this case I'm getting timeout issue instead of issue with root not existing. But I think it's still the same issue.

I found that the issue might be related to using EventTarget instance. The only fact of creating an new instance of an EventTarget will cause loki to fail.
Please see it here https://github.com/gsouf/loki-issue/blob/d04866eca1e9f853c6f49bc83fb20e3da332088b/src/EventComponent.jsx#L16

If I knew how to get error logs then I could probably help at fixing it.

**Comment by gsouf** [comment]
@oblador I confirm something is going wrong with the EventTarget object in loki env.

If I add this polyfill then it works https://github.com/ungap/event-target

**Comment by oblador** [comment]
There is no "`loki` environment" really. It runs chrome and you can select which version to run with the `chromeDockerImage` option (even make your own build). Currently the default value is `yukinying/chrome-headless:63.0.3230.2` which is quite old, cause I didn't want to break existing installations unnecessarily, but in retrospect I should have bumped it when i recently made other breaking changes. 

To see if it solves your issue, could you pick one from one of the [more recent builds](https://hub.docker.com/r/yukinying/chrome-headless-browser/tags) like `--chromeDockerImage yukinying/chrome-headless-browser:85.0.4181.8`?

**Comment by gsouf** [comment]
@oblador thanks for the output. I see that EventTarget constructor was implemented in chrome 64, that would indeed explain why it fails. I'm going to upgrade my docker image as you suggested.

**Comment by oblador** [comment]
Great, I'll look at making a PR bumping the default version too!
