### ISSUE TITLE
Question: Can I skip multiple stories with the same name?

### ISSUE THREAD

**Issue by felixkeller98** [oblador/loki#251]
Every component in my Storybook has an 'overview'-Story which contains each of its variants.
For example my Button-Component looks like this:
```js
storiesOf('Button', module)
  .add('overview', () => (
    <>
           <Button small>Small</Button>
           <Button>Default</Button>
           <Button large>Large</Button>
    </>
   ))
  .add('small', () => <Button small>Small</Button>)
  .add('default', () => <Button>Default</Button>)
  .add('large', () => <Button large>Large</Button>)
...
```

Is it possible with Loki to skip the "overview" story for all my components in a somewhat elegant way? 

Im aware of the method for skipping single Stories, by passing the setting `skip: true` in the `loki` parameter, but I was wondering how one could handle such a case.

**Comment by oblador** [comment]
While deprecated and will be removed in a future version, you can set the `skipStories` option in your settings to acheive this.
