### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by RyanHow** [oblador/loki#255]
Hi!

Just wondering if Loki supports Storybook Angular?

A quick test results in errors on storybook

```
ERROR in ./.storybook/config.js
Module not found: Error: Can't resolve 'loki/configure-react'
```

Thanks!

**Comment by techeverri** [comment]
Hey @RyanHow 👋 

Could you please share the example project that you used to get the error?

**Comment by RyanHow** [comment]
Hi @techeverri 

So sorry for the long delay.

Here's a minimal repo here with Angular, Storybook and Loki

https://github.com/RyanHow/Loki-test

Just

`npm install`
`npm run storybook`

**Comment by techeverri** [comment]
Have you tried removing the line below (highlighted in yellow)? @RyanHow 

![image](https://user-images.githubusercontent.com/3720424/89698491-db9eff80-d921-11ea-927f-6b8bce422c1f.png)
🔗  https://github.com/RyanHow/Loki-test/blob/9d8c4cdb8cfe353affa365bd78fcffea3d5a0106/src/index.stories.js#L2

**Comment by techeverri** [comment]
The error message that you see in the terminal is not from Loki but from Storybook

**Comment by techeverri** [comment]
Also make sure to configure Loki as described in the installation docs 👇 
🔗  https://github.com/oblador/loki#installation

_Note: it doesn't automatically identify that is an Angular project but that's a different issue. I'll have a look at that later_

**Comment by RyanHow** [comment]
Thanks!

If I remove the import, storybook compiles, but Loki won't run.

`Loki addon not registered. Add `import 'loki/configure-react'` to your .storybook/preview.js file.`

**Comment by RyanHow** [comment]
I've updated the repo and added in the `preview.js` file, which appears to be executed in the preview frame.

I've put in what I think is an angular equivalent to `import 'loki/configure-react'`, however I'm still getting the same error.

You can reproduce with

```
npm install
npm run storybook
npm run loki -- update
```

**Comment by RyanHow** [comment]
Any pointers where to look?

I've popped this in the `preview.js`

```
const storybook = require('@storybook/angular');
const { createStorybookConfigurator } = require('@loki/browser');
createStorybookConfigurator(storybook);
```

but I still get the error `Loki addon not registered. Add import 'loki/configure-react' to your .storybook/preview.js file.`
