### ISSUE TITLE
how to use `lokiAsync` with web components? 

### ISSUE THREAD

**Issue by Felistas** [oblador/loki#264]
Example:
//test.stories.ts
```

storiesOf('testStory', module)
  .add('synchronous story', () => <test-component>)
  .lokiAsync('asynchronous story', ({ done }) => <test-component onDone={done} />);
```

![image](https://user-images.githubusercontent.com/17156765/92741310-c1bc6680-f37e-11ea-814d-6358ecc9724b.png)

//test.ts
```
import {css, customElement, html, LitElement} from 'lit-element';
@customElement('test-component')
export class MicContentBox extends LitElement {

}
```

**Comment by oblador** [comment]
Hey, try using the `@loki/create-async-callback ` package as outlined here https://loki.js.org/flaky-tests.html#asynchronous-stories
