### ISSUE TITLE
For chrome.docker, loki is using unstable chrome versions.

### ISSUE THREAD

**Issue by innovation16** [oblador/loki#267]
For chrome.docker, loki uses this image: yukinying/chrome-headless-browser which uses an unstable version of chrome.
What is the reasoning for it? Can we use an image that uses stable chrome version?

**Comment by myxious** [comment]
Actually it uses `yukinying/chrome-headless-browser:85.0.4181.8`. The last stable chrome version is `85.0.4183.102`.
But you can use your own docker image with any chrome version you want. 
Just run loki with `--chromeDockerImage="myDockerImage"` argument.
