### ISSUE TITLE
How can I debug a loki test while running it on docker?

### ISSUE THREAD

**Issue by innovation16** [oblador/loki#268]

**Comment by techeverri** [comment]
It depends, What you mean by "debug a loki test"?

**Comment by techeverri** [comment]
You can debug Loki itself (JavaScript) using Node.js and it doesn't require Docker

- Run the following command to run Node.js in debug mode

```bash
❯ node --inspect-brk node_modules/.bin/loki
```

- Open [chrome://inspect/]() and click "Open dedicated DevTools for Node"

- Once the DevTools connected to Node.js you'll be able to set breakpoints (e.g. programmatically using `debugger;`)

### References

- 🔗  https://flaviocopes.com/node-debug-devtools/
- 🔗  https://nodejs.org/en/docs/guides/debugging-getting-started/
- 🔗  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger

Hope it helps! 👍
