### ISSUE TITLE
Deprecated setAddon usage

### ISSUE THREAD

**Issue by rodsscg** [oblador/loki#270]
The project is using the deprecated setAddon method (`@loki/integration-core/src/decorate-storybook.js`), and according to the Storybook, it will be removed on version 7; This is creating the following warning on projects:

![image](https://user-images.githubusercontent.com/56806457/94350648-a0b66f80-0026-11eb-89ef-b747b4874a24.png)

**Comment by oblador** [comment]
Hey! Loki no longer depends on `setAddon`, you can safely delete the integration and it should work!

**Comment by qooban** [comment]
@oblador I can help with this issue. Just need to understand if I get it right that we can just remove:
```
  storybook.setAddon({
    lokiSkip: function(...args) {
      return wrapWithSkipStory(this.add.bind(this), this.kind)(...args);
    },
    lokiAsync: function(...args) {
      return wrapWithAsyncStory(this.add.bind(this))(...args);
    },
    lokiAsyncSkip: function(...args) {
      return wrapWithSkipStory(
        wrapWithAsyncStory(this.add.bind(this)),
        this.kind
      )(...args);
    },
  });
```
from https://github.com/oblador/loki/blob/master/packages/integration-core/src/decorate-storybook.js?

If so, I can create PR.

**Comment by oblador** [comment]
You can completely remove the register addon import. I'm keeping it around for now to not break existing installations.
