### ISSUE TITLE
Missing @loki/runner/src/commands/test folder

### ISSUE THREAD

**Issue by kurttomlinson** [oblador/loki#274]
I'm fairly certain this isn't an issue with Loki itself, but I don't know where else to ask for support on this. So I'm sorry to bother you, and thanks in advance for any help!

I ran the commands below in my monorepo project:

```
yarn workspace marketing-pages add loki
yarn workspace marketing-pages loki init
yarn workspace marketing-pages storybook
yarn workspace marketing-pages loki update
```

The final command, `loki update` gives me the error `UnhandledPromiseRejectionWarning: Error: Cannot find module './commands/test'`:

![image](https://user-images.githubusercontent.com/1914753/95530808-d22b2580-09ac-11eb-8bf7-b7ce8b7fa81a.png)

I checked in my node_modules folder, and sure enough, there was no `commands/test` folder:

![image](https://user-images.githubusercontent.com/1914753/95530582-3ac5d280-09ac-11eb-943e-e9b03b4c5f17.png)

I figured this was probably the result of a corrupt yarn cache, so I ran `yarn cache clean` and repeated the process again. I got the same results the second time. I'm using yarn v1.22.4.

Does anyone have any ideas why I'm getting an incomplete `loki` package?

**Comment by kurttomlinson** [comment]
I figured this out! There was a `test` line in the `.yarnclean` file.

**Comment by techeverri** [comment]
Today I Learned: `yarn autoclean --force` is a thing 🤯 
🔗 https://classic.yarnpkg.com/en/docs/cli/autoclean/
