### ISSUE TITLE
Disable diffing

### ISSUE THREAD

**Issue by atiredturtle** [oblador/loki#287]
Loki is great for generating good snapshots from storybooks, but a diffing engine must be provided.
This means an alternative diffing engine can't be used without redoing a bunch of the same work. 
is there a way to disable the diffing engine? So we just generate the snapshots?

**Comment by techeverri** [comment]
Use the `loki update` command instead of `loki test` and it will capture screenshots and update the reference files without diffing

🔗 https://loki.js.org/command-line-arguments.html#loki-update
