### ISSUE TITLE
TypeError: Cannot read property 'assign' of undefined

### ISSUE THREAD

**Issue by erochOnGit** [oblador/loki#3]
hello,
I have my storybook running on localhost:9001
I run yarn loki init in my react project 
then yarn loki update -- --port 9001 
and loki tell me : 
yarn loki v0.27.5
$ "/home/emile/projet/front-commerce/node_modules/.bin/loki" "update" "--port" "9001"
loki update v0.5.3
 ❯ Chrome (docker)
   ✔ Start
   ✖ Fetch list of stories
     → Cannot read property 'assign' of undefined
     Test chrome.laptop
     Stop
TypeError: Cannot read property 'assign' of undefined
error Command failed with exit code 1.

could you help me to find out what's going wrong ?

**Comment by oblador** [comment]
Hi, what version of node are you on?

**Comment by erochOnGit** [comment]
node -v
v7.10.1

**Comment by erochOnGit** [comment]
I'm on ubuntu if it's could help

**Comment by erochOnGit** [comment]
I think the error is from:
vm.runInNewContext(bundle, sandbox); of fetch-storybook.js
But i'm not able dig into it, do you have some idea ?

**Comment by erochOnGit** [comment]
I said I cannot dig ... but i lied... ^^'
Looking at this issue https://github.com/facebook/jest/pull/2021 
The guy has a project that look like yours! I mean with the vm the jsdom etc... and he had face my issue because jsdom actually in loki does not provide Object in the sandbox

The correction that he found is in this ticket : https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global

I hope you could look this and upgrade your project on my side i'll make a new react project with a clean storybook to run loki

**Comment by oblador** [comment]
Hi, thanks for digging, think I need to dig some more as well. Can you give me some minimal sample code to reproduce this? Assuming you have some client side code that expects `Object.assign` right? What's your babel config looking like?

**Comment by erochOnGit** [comment]
I think that your code expect Object.assign and mine defined it earlier and that creating an issue, I tried to make a project with docker .. it works! then i'll try to add rxjs (<- that defining Object.assign) and then I think i'll reproduce the issue. When it's done I'll commit to a public repo and give it to you ;)

**Comment by erochOnGit** [comment]
actually, I can run loki outside a docker and use a storybook in docker but not loki in docker... I get a timeout at the start step

**Comment by erochOnGit** [comment]
In order to reproduce the same exact bug I face a new one ... i'll open an other issue

**Comment by oblador** [comment]
Hmm, not sure maybe it times out when downloading the image the first time.

**Comment by real34** [comment]
Hi, we spent a few time to dig further and it appears that the timeout was due to https://github.com/oblador/loki/blob/af9d46c0b4ffac7a5692b4304ea5d1d3fe8f91d0/src/targets/chrome/docker.js#L28

Changing `localhost` to `172.17.0.1` (the docker IP) solved the timeout, I am not sure how to get this environment fact from node. Maybe `os` something?

However it then tries to access stories on an invalid port:

```
$ "/project/node_modules/.bin/loki" update --host 172.17.0.10 --port 9009 --requireReference
loki update v0.6.0
 ❯ Chrome (docker)
   ✔ Start
   ✔ Fetch list of stories
   ❯ Test chrome.laptop
     ❯ Welcome
       ✖ to Storybook
         → connect ECONNREFUSED 127.0.0.1:39559
     ❯ Button
       ✖ with text
         → connect ECONNREFUSED 127.0.0.1:39559
       ✖ with some emoji
         → connect ECONNREFUSED 127.0.0.1:39559
   ✔ Stop
Some visual tests failed to run
```

That is our current status...

**Comment by oblador** [comment]
I think it tries to access Chrome Remote Debugger at port 39559, unsure why it's not responding.

Can you try building a static bundle and passing `--reactUri file:./storybook-static`?

**Comment by oblador** [comment]
JSDOM has been removed as of [0.10.0](https://github.com/oblador/loki/releases/tag/v0.10.0). 👍
