### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by Abhijeetjaiswalit** [oblador/loki#318]
Hi @oblador @erzhtor 

I've implemented this awesome library in our react project(storybook), everything is perfect.

Only issue that i am facing and kind of stuck onto is: 

I dockerized the loki test setup to use it in a pipeline in teamcity.
so while testing that setup, i'm facing issue where, tests are failing.

Steps that i used with my docker setup is - 

1) Updated the reference screenshots using - loki update --reactUri="file:./storybook-static" --chromeFlags="--headless --no-sandbox"
2) and then run the docker

My dockerfile setup is - 

`FROM node:12.20.0 AS base

# Install Chrome

RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add - \
  && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list \
  && apt-get update -qqy \
  && apt-get -qqy install google-chrome-unstable \
  && rm /etc/apt/sources.list.d/google-chrome.list 

ENV CHROME_BIN /usr/bin/google-chrome

RUN set -x \
    && node -v \
    && npm -v \
    && google-chrome --version

WORKDIR /app
COPY ["package.json", "yarn.lock", ".yarnrc", ".npmrc", "./"]

RUN yarn install
COPY . .

_CMD yarn build-storybook --static-dir ./public && yarn loki --requireReference --reactUri="file:./storybook-static" --chromeFlags="--headless  --no-sandbox"_
`

the issue that i'm getting at the end is - 

`
RUNS chrome.app
RUNS chrome.app/START
PASS chrome.app/START
RUNS chrome.app/FETCH_STORIES
PASS chrome.app/FETCH_STORIES
RUNS chrome.app/TESTS
RUNS chrome.app/chrome.laptop/Banner/Banner
RUNS chrome.app/chrome.laptop/Button/Button
RUNS chrome.app/chrome.laptop/Card/Card
RUNS chrome.app/chrome.laptop/Card/Home Page Cards
FAIL chrome.app/chrome.laptop/Banner/Banner: Screenshot differs from reference, see .loki/difference/chrome_laptop_Banner_Banner.png
RUNS chrome.app/chrome.laptop/CheckBox/CheckBox Enabled
FAIL chrome.app/chrome.laptop/Button/Button: Screenshot differs from reference, see .loki/difference/chrome_laptop_Button_Button.png
FAIL chrome.app/TESTS: Some tasks failed to run
FAIL chrome.app: Some tasks failed to run
Visual tests failed
You can update the reference files with:
loki update --reactUri="file:./storybook-static" --chromeFlags="--headless  --no-sandbox"    
error Command failed with exit code 1.
`

i've also tried using different versions of node. still no luck.

can you have a look please, i might be missing some very basic thing.

every thing works perfect if i try to run the test using the same setup (without docker)

my loki config is 

`
"loki": {
    "configurations": {
      "chrome.laptop": {
        "target": "chrome.app",
        "width": 1366,
        "height": 768,
        "deviceScaleFactor": 1,
        "mobile": false,
        "fitWindow": false
      }
    }
  }
`

**Comment by oblador** [comment]
Hi, do you run loki in a docker container both locally and in CI?

**Comment by Abhijeetjaiswalit** [comment]
@oblador 

yes. 

on local just for the testing purpose i ran docker container. but the tests are failing. idea was to use the docker container only in CI

**Comment by oblador** [comment]
@Abhijeetjaiswalit The point of the docker container is to ensure the environment is identical everywhere, so for it to work you need to run docker locally too and update those baselines to match it.  You can check the [example project](https://github.com/oblador/loki/blob/master/examples/react/loki.config.js) for reference.

**Comment by Abhijeetjaiswalit** [comment]
@oblador 
thanks for your quick response, though i understand the purpose of docker container, the problem is, when i run the container on local, the tests are failing, so i was wondering, what might be the reason of failed test cases.
Sorry, if wasn't clear before.

**Comment by Abhijeetjaiswalit** [comment]
So, after spending so many hours, got to know, the reason of failure was the way I was creating screenshots reference. I was creating the reference using chrome.app and was trying to run the test in docker because of which the test cases was failing.

Solution was - the reference images also needed to be created inside docker container or using chrome.docker not on local machine using chrome.app.

 Hence closing this.
