### ISSUE TITLE
Failed to render with error "(0 , _jsxDevRuntime.jsxDEV) is not a function"

### ISSUE THREAD

**Issue by ara2202** [oblador/loki#321]
I use loki cli like this:

`loki --reactUri file:../.storybook/storybook-static --chromeDockerUseCopy --useRelativePath --chromeFlags=\"--headless --disable-web-security --no-sandbox --hide-scrollbars --disable-gpu --disable-setuid-sandbox\"`

After I run this I get a bunch of errors saying `Failed to render with error "(0 , _jsxDevRuntime.jsxDEV) is not a function"`

I assume it is related to [new jsx transform by React](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html).

But I can't make it to work. Any ideas on how to do it?

**Comment by techeverri** [comment]
Check this discussion from the Babel repo https://github.com/babel/babel/discussions/13013 that seems related to the error you're getting

**Comment by techeverri** [comment]
Closing as this is not caused or related to Loki
