### ISSUE TITLE
How to use loki async callback function with CSF in Angular? 

### ISSUE THREAD

**Issue by alexanderfink** [oblador/loki#332]
Hello, 

is it possible to use place a async callback function with CSF in Angular? Could not find any example. 

```
export const DataTableDefault = () => {
  return {
    component: DataTableComponent,
    props: {
      columns: createTableColumns(),
      dataSource: createTableRows()
    }
  };
};
```

**Comment by techeverri** [comment]
Have you tried using `@loki/create-async-callback`?

🔗 https://loki.js.org/flaky-tests.html#asynchronous-stories
![image](https://user-images.githubusercontent.com/3720424/130229996-7b6b2e49-b35a-44d3-b06f-7f4a389528b7.png)

### Context

Support for async CSF stories was introduced by https://github.com/oblador/loki/pull/258

### Examples

https://github.com/oblador/loki/blob/8beda16fcda4841c4e23c7353880e94498cbadcc/examples/react-native/storybook/stories/index.js#L58-L60

https://github.com/oblador/loki/blob/8beda16fcda4841c4e23c7353880e94498cbadcc/examples/react/src/stories/index.stories.js#L39-L41

**Comment by techeverri** [comment]
For questions, I'd recommend you to use the Discussion tab
🔗 https://github.com/oblador/loki/discussions

**Comment by alexanderfink** [comment]
Hey, thank you for your answer. Unfortunately I could not manage to write a story in the storiesOf Format using Angular. Could you be so kind and provide a story example using Angular and storiesOf or SCF with async stories. 

Sadly the [extended readme](https://github.com/storybookjs/storybook/blob/master/lib/core/docs/storiesOf.md) could not provide any information on this. 

Will post questions in the discussion tab the next time. Thanks

**Comment by d3vl1m3** [comment]
Yeah - the stories of is legacy now. Does Loki allow for this to be written in the standard export format now?
