### ISSUE TITLE
Build Script 

### ISSUE THREAD

**Issue by siyavash4812** [oblador/loki#338]
I am trying to add [odiff](https://github.com/dmtrKovalenko/odiff) to this project but I cannot build the repo to make sure it is working as expected. I want to install the package using my forked version but I keep getting the full source code rather than the build files. 

Does anyone know how I can get the build/dist files?
Thank you

**Comment by techeverri** [comment]
For questions, I'd recommend creating a new “discussion” here 👇 
🔗 https://github.com/oblador/loki/discussions
