### ISSUE TITLE
Dependency conflict with @storybook/react 6.4.0

### ISSUE THREAD

**Issue by bryanjtc** [oblador/loki#349]
![image](https://user-images.githubusercontent.com/49354825/143136509-ca483e61-a9b7-41b5-953f-1e20ff9a34bf.png)
In the coming days storybook is going to release v6.4.0. I decided to try the latest release candidate and I noticed a dependency conflict with loki. Can this be fixed in a new release?

**Comment by techeverri** [comment]
Does it work now? @bryanjtc

**Comment by bryanjtc** [comment]
It seems to work with the latest version, 6.4.9.
