### ISSUE TITLE
Fails on CI with Timeout onTimeout

### ISSUE THREAD

**Issue by felquis** [oblador/loki#38]
I'm setting up the loki + storybook, I installed loki as follows:
```
  "devDependencies": {
    "loki": "oblador/loki"
  },
  "loki": {
    "diffingEngine": "looks-same",
    "configurations": {
      "chrome.palm": {
        "target": "chrome.docker",
        "width": 640,
        "height": 480,
        "deviceScaleFactor": 1,
        "mobile": false,
        "fitWindow": false
      }
    }
  }
```

On CI is throws 
```
     Fetch list of stories
     Test chrome.palm
     Stop
Timeout
Error: Timeout
    at Timeout._onTimeout (/home/circleci/repo/webapp/node_modules/wait-on/lib/wait-on.js:91:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

Here is [the log](https://circleci.com/gh/pagarme/pilot/734), this time it also does't work on my machine.

**Comment by oblador** [comment]
Hi, it seems to time out starting docker, so likely you're fetching the new docker image (I recently changed). It's on my todo to be more transparent to the user when this happens and to have a longer timeout in those cases. But meanwhile, can you try to up [this number](https://github.com/oblador/loki/blob/7af2feb16f8cf01ff711c654636846d832fa8cbd/src/targets/chrome/docker.js#L31) locally and see if that helps?

**Comment by felquis** [comment]
Totes, I'll try it soon

**Comment by oblador** [comment]
@felquis any luck?

**Comment by nuc** [comment]
@oblador Yup, that helps. Maybe we should make the timeout configurable.
