### ISSUE TITLE
Feature Request: "prune" command to delete unused reference images

### ISSUE THREAD

**Issue by markbrockhoff** [oblador/loki#380]
Hi, first of all thanks for this amazing tool. ❤️ 

I noticed that there is currently no automated way to get rid of unused reference images.
So for example after deleting the story of a component the reference image of it just stays inside the reference folder.
It's not a big deal but it would be really nice to have a cli command like `loki prune` to delete all reference images without a matching story.

**Comment by techeverri** [comment]
As mentioned here https://github.com/oblador/loki/issues/236#issuecomment-653240530 there is already another command that does that by default

https://loki.js.org/command-line-arguments.html#loki-approve

> `loki approve`
> Prunes old and updates reference files with the images generated in the last run.

**Comment by markbrockhoff** [comment]
Oh I absolutely overlooked that. Thanks a lot @techeverri 👍

**Comment by vogelino** [comment]
This is great! However if you've already committed in the past outdated references, those won't be deleted. It would be awesome to be able to prune every reference that doesn't match any existing story, independently from the last run. I usually remove all references and run update again to only generate those from the existing stories, but I'm working on a huge codebase and this takes quite a while. This is nitpicking though. :)
