### ISSUE TITLE
My Vue project loki test failed with new  loki version v0.30.0

### ISSUE THREAD

**Issue by indrasenakatam** [oblador/loki#392]
We have build VUE js application and integrated storybook and loki for visual regression testing with story book.
with loki 0.29.0  all my storybook images testing fine.

Recently the new loki version 0.30.0 the test failed without changing UI. 
If I reverted to loki version 0.29.0  then again my loki test pass using existing reference images.

So can you please help me, **why loki test failed with existing reference images using loki version 0.30.0** without changing any code.

**please find the loki test command.**
time yarn loki test \
        --reactUri file:./storybook-static \
        --chromeFlags='--headless --disable-gpu --hide-scrollbars --no-sandbox' \
        --requireReference \
        --verboseRenderer

please update if you need any additional info on this. Thank you in advance.

**Comment by oblador** [comment]
Hi, It's quite possible this is related to the updated version of chrome. What are the exact failure messages? You can try to use the old chrome image by passing `--chromeDockerImage "yukinying/chrome-headless-browser:90.0.4408.0"`.

**Comment by indrasenakatam** [comment]
Hi @oblador  Thank you for quick response.

I have tried with below command it's working fine with **OLD** existing reference images using loki version 0.30.0.

time **yarn loki test** \
--reactUri file:./storybook-static \
--chromeFlags='--headless --disable-gpu --hide-scrollbars --no-sandbox' \
--requireReference \
--verboseRenderer \
--**chromeDockerImage**	='**yukinying/chrome-headless-browser:90.0.4408.0**'


Could you please help me on below clarifications.

- How can we come to know the suitable chrome docker image version for respective to loki version 
https://github.com/oblador/loki/compare/v0.29.0...v0.30.0

- Can we do **loki-update** for updating existing reference images with new docker chrome version. Is there any advantages as compared to old chrome version (could you please doc if we have) and we don't have any chrome browser version dependency. What would you suggest on this ..?


I am grateful for your support.

**Comment by oblador** [comment]
The main advantage with the new image is that it natively support M1 Macs, but another is that it's using a more recent version of Chrome meaning it will be closer to what the typical end user will see. You can choose to stay on the old version or update baselines, (just make sure to validate the changes to make sure they are what you intend).

**Comment by indrasenakatam** [comment]
Thank you @oblador  for your support. 
Closing issue.
