### ISSUE TITLE
ECONNREFUSED error again on windows

### ISSUE THREAD

**Issue by bonesoul** [oblador/loki#405]
although i've commented here https://github.com/oblador/loki/issues/369 i wanted to create a new issue as the old one is already closed.

still getting the error with windows witn node 18.

```
λ loki update
loki update v0.30.3
 FAIL  chrome.app
       Fetching stories
       connect ECONNREFUSED ::1:55504
Some visual tests failed to run
```

any chances to test with chrome-launcher 0.15.1?

**Comment by techeverri** [comment]
You can try updating `chrome-launcher` and testing on your Windows machine @bonesoul
Feel free to open a pull request with the dependency update, if that fixes it 👍

**Comment by vladbulyukhin** [comment]
I also encountered this problem. It turned out that in my case, it was not `chrome-launcher`, but `chrome-remote-interface` that caused it. I created a PR (#418) with a newer version of `chrome-remote-interface`, but overriding the `chrome-remote-interface` version in your package.json also helps and can be used as a workaround.

**Workaround**
```
// package.json
{
  "overrides": {
    "chrome-remote-interface": "0.31.3"
  },
}
```

**Comment by AiranBalor** [comment]
> I also encountered this problem. It turned out that in my case, it was not `chrome-launcher`, but `chrome-remote-interface` that caused it. I created a PR (#418) with a newer version of `chrome-remote-interface`, but overriding the `chrome-remote-interface` version in your package.json also helps and can be used as a workaround.
> 
> **Workaround**
> 
> ```
> // package.json
> {
>   "overrides": {
>     "chrome-remote-interface": "0.31.3"
>   },
> }
> ```

Did't work, still got same error

**Comment by vladbulyukhin** [comment]
> > I also encountered this problem. It turned out that in my case, it was not `chrome-launcher`, but `chrome-remote-interface` that caused it. I created a PR (#418) with a newer version of `chrome-remote-interface`, but overriding the `chrome-remote-interface` version in your package.json also helps and can be used as a workaround.
> > **Workaround**
> > ```
> > // package.json
> > {
> >   "overrides": {
> >     "chrome-remote-interface": "0.31.3"
> >   },
> > }
> > ```
> 
> Did't work, still got same error

@AiranBalor that's strange. It worked for me, I use it as a workaround in my GitHub Action. Have you tried removing `node_modules` and `package-lock.json` and re-installing everything after adding "overrides" to your `package.json`?

**Comment by AiranBalor** [comment]
@vladbulyukhin I did, but still I get the same error. I using chrome.docker instead chore.app, that help.

**Comment by romanovvINC** [comment]
anybody has got fix?
