### ISSUE TITLE
Loki failing when app is requesting files with a slower than expected response/download time in the DOM

### ISSUE THREAD

**Issue by d3vl1m3** [oblador/loki#407]
So - running this in a clean CRA + npx SB init + Loki environment, it seems to be that having a src in the video element breaks it.

Error in loki is:

```
 FAIL  chrome.docker/chrome.laptop/Example/Video
       Video
       1 request failed to load; 
```

Specifically seems to be related to the `src` attribute on the `source` element as when this is removed it will work.

Video.stories.jsx

```js
import React from 'react';

export default {
  title: 'Example/Video',
  parameters: {
    // More on Story layout: https://storybook.js.org/docs/react/configure/story-layout
    layout: 'fullscreen',
  },
};

const Template = () => <video controls="" controlsList="nodownload" poster="https://images-na.ssl-images-amazon.com/images/I/51s0Nl7DVSL._SL500_AC_SS350_.jpg">
  <source src="https://www.w3schools.com/tags/movie.mp4" type="video/mp4"/>
</video>;

// More on interaction testing: https://storybook.js.org/docs/react/writing-tests/interaction-testing
export const Video = Template.bind({});

```

**Comment by d3vl1m3** [comment]
iframe code example
```

    <iframe
      loading="lazy"
      title="YouTube"
      src={`https://www.youtube${youTubeParameter}.com/embed/${youTubeId}`}
      frameBorder="0"
      allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
      allowFullScreen
    />
```

**Comment by d3vl1m3** [comment]
Now I#m looking at it... I'm getting a bad feeling about the lazy loading tag... Will dig at it.

**Comment by d3vl1m3** [comment]
So - running this in a clean CRA + npx SB init + Loki environment, it seems to be that having a src in the video element breaks it.

**Comment by d3vl1m3** [comment]
Video.stories.jsx

```js
import React from 'react';

export default {
  title: 'Example/Video',
  parameters: {
    // More on Story layout: https://storybook.js.org/docs/react/configure/story-layout
    layout: 'fullscreen',
  },
};

const Template = () => <video controls="" controlsList="nodownload" poster="https://images-na.ssl-images-amazon.com/images/I/51s0Nl7DVSL._SL500_AC_SS350_.jpg">
  <source src="https://www.w3schools.com/tags/movie.mp4" type="video/mp4"/>
</video>;

// More on interaction testing: https://storybook.js.org/docs/react/writing-tests/interaction-testing
export const Video = Template.bind({});

```

**Comment by d3vl1m3** [comment]
Seems to specifically be an issue with the default docker image. 

If I set my config from:
```
  "loki": {
    "fetchFailIgnore": true,
    "configurations": {
      "chrome.laptop": {
        "target": "chrome.docker",
        "width": 1440,
        "height": 800
      }
    }
  }
```
to
```
  "loki": {
    "fetchFailIgnore": true,
    "configurations": {
      "chrome.laptop": {
        "target": "chrome.app",
        "width": 1440,
        "height": 800
      }
    }
  }
```

The tests fail.

**Comment by d3vl1m3** [comment]
I've updated this to pull from a local file and is still failing on the docker app.

Running: `npm run build-storybook -s public && loki update --reactUri=file:./storybook-static`

Seems to work a treat with the local file version. 

Can anyone offer insight/fix please? :)

**Comment by d3vl1m3** [comment]
Okay! I have a workaround. I've set `<video [...] preload="none">` on the element and this seems to placate the screenshot. 

I think this still loops back around to having an easy to configure way of adding a delay to the screenshot of an individual/all stories.

**Comment by d3vl1m3** [comment]
All sorted. No longer an issue. I managed to add a delay to the story using `import createAsyncCallback from '@loki/create-async-callback';` and a custom `DelayCapture` component (added to the story template).

Full solution here https://github.com/oblador/loki/discussions/384

**Comment by Anxhul10** [comment]
I'm running into a limitation when using a delay hook in a Storybook story like an AudioPlayer component.

When I configure Loki to run across multiple screen sizes (e.g., mobile, tablet, desktop), the delay hook works only for the one viewport . In earlier viewports, Loki resizes the page without waiting for the delay to complete before taking the screenshot.

This results ``` request failed to load; ```

```
// package.json

"loki": {
    "configurations": {
      "desktop": {
        "target": "chrome.docker",
        "width": 1440,
        "height": 896,
        "deviceScaleFactor": 1,
        "mobile": false,
        "fitWindow": false
      },
      "tablet": {
        "target": "chrome.docker",
        "width": 768,
        "height": 970,
        "deviceScaleFactor": 1,
        "mobile": false,
        "fitWindow": false
      },
      "mobile": {
        "target": "chrome.docker",
        "preset": "iPhone 7"
      }
    }
  }
```

**Comment by Anxhul10** [comment]
I somehow got the overview why this error occurs , and why it is solved then `fetchFailIgnore:".*"` is added , as mentioned in the docs loki default behaviour is to fail the test if there is fail network request (even thought you can get the snapshot of the component).
I was getting this error in AudioPlayer where this component by default fetches the url to get the audio sample, but on runnning loki fetch request fails. 

used isLokiRunning() utility to conditionally check whether loki is running or not . If running donot make fetch request.
