### ISSUE TITLE
Feature request: set chromeFlags from loki.config.js

### ISSUE THREAD

**Issue by samboylett** [oblador/loki#415]
Hey

I've set Loki up on an existing app with many stories. To avoid flaky issues between runs, I've had to enable 20+ chrome flags. Could we add a setting to loki.config.js for chrome flags as well as the CLI option? Having such a long list set in my npm scripts is not great!

I was thinking something like this:

```javascript
module.exports = {
  chromeFlags: [
    '--headless',
    '--other-flags',
    // etc.
  ],
  // other config etc.
  diffingEngine: "looks-same",
  configurations: {
    // etc.
  }
};
```

Cheers

**Comment by oblador** [comment]
Hi, this should be possible on a per configuration basis, but must currently be a string due to how the parsing works. So you'd do something like this:

```js
const chromeFlags = '--headless --other-flags';

module.exports = {
  diffingEngine: "looks-same",
  configurations: {
    'iphone.docker': {
      chromeFlags,
    }
  }
};
```

**Comment by samboylett** [comment]
Ah thanks, this solves my use case :)

**Comment by oblador** [comment]
Might I ask which flags you use and where you see flake? Could perhaps be useful to add to the standard set.
