### ISSUE TITLE
Loki into GitLab CI not working.

### ISSUE THREAD

**Issue by alles** [oblador/loki#421]
Hello!

Thanks for this awesome project! :)

I have the problem in GitLab-CI. When I run CI in the gitlab I got error.

> $ loki --reference=regress/loki --reactUri file:./build/storybook
> loki test v0.30.3
> You can download it from https://www.docker.com/
> FAIL chrome.docker/PREPARE: Docker is not installed

When I use **docker in docker** image in my ci I got error

`FAIL chrome.docker/START: Chrome failed to start with errors "[1023/165803.093097:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory`

I tred change images, I tred set a docker volume `/run/dbus/system_bus_socket` for my container, but this is not helpful.

How can run loki into GitLab CI? Please help me.

Thanks.

**Comment by AntonNiklasson** [comment]
I ran into the same problem. Here's my current config:

```
// loki.config.js

const target = process.env.CI ? 'chrome.app' : 'chrome.docker'

const slugify = raw =>
  raw
    .replace(' ', '-')
    .replace('/', '_')
    .replace(/[^a-z0-9-_]/gi, '')
    .toLowerCase()

module.exports = {
  diffingEngine: 'gm',
  fileNameFormatter: ({ configurationName, kind, story }) =>
    `${slugify(configurationName)}__${slugify(kind)}__${slugify(story)}`,
  configurations: {
    desktop: {
      target: target,
      preset: 'Retina Macbook Pro 15',
    },
    mobile: {
      target: target,
      preset: 'iPhone 7',
    },
  },
}
```

**Comment by mhsfh** [comment]
> I ran into the same problem. The solution for me was to run with the app inside the container. Here's my current config:
> 
> ```
> // loki.config.js
> 
> const target = process.env.CI ? 'chrome.app' : 'chrome.docker'
> 
> const slugify = raw =>
>   raw
>     .replace(' ', '-')
>     .replace('/', '_')
>     .replace(/[^a-z0-9-_]/gi, '')
>     .toLowerCase()
> 
> module.exports = {
>   diffingEngine: 'gm',
>   fileNameFormatter: ({ configurationName, kind, story }) =>
>     `${slugify(configurationName)}__${slugify(kind)}__${slugify(story)}`,
>   configurations: {
>     desktop: {
>       target: target,
>       preset: 'Retina Macbook Pro 15',
>     },
>     mobile: {
>       target: target,
>       preset: 'iPhone 7',
>     },
>   },
> }
> ```

@AntonNiklasson which docker image did use in gitlab-ci?

**Comment by AntonNiklasson** [comment]
We used a custom built image for that. But that wasn't complex at all, just install the chrome browser and have it available for loki to use

**Comment by p3k** [comment]
> We used a custom built image for that. But that wasn't complex at all, just install the Chrome browser and have it available for loki to use

@AntonNiklasson would be interested in the details… I got a working Docker container that runs google-chrome by default. How would I use that with Loki now?
