### ISSUE TITLE
`chrome.docker` differences when running in CI compared to on MacOS

### ISSUE THREAD

**Issue by freshollie** [oblador/loki#434]
Hi,

I would expect `chrome.docker` to have the same rendering on any machine, however we are noticing really tiny differences when running in CI:

![diff](https://user-images.githubusercontent.com/11363036/216027040-cb36c0f7-47e6-4f7b-9754-8e43b5926b8e.png)

This is a canvas rendered graph, but again in docker I would expect everything to be the same.

Are there any options I can specify to improve this?

**Comment by techeverri** [comment]
Have you tried using `chromeTolerance`? _Supported by `gm` and `looks-same`_

- https://github.com/oblador/loki/blob/master/docs/configuration.md#gm
- https://github.com/oblador/loki/blob/master/docs/configuration.md#looks-same

**Comment by freshollie** [comment]
It can be fixed with tolerance, however I'm more wondering why there would be any rendering differences at all? If the snapshots run in docker on one environment shouldn't they look the same if they also run in docker on another environment?

Sidenote: Is `chromeTolerance` not supported by `pixelmatch`? When I set this to `1` (% I assume?) then these tests pass.

**Comment by Manishy-97** [comment]
Hey folks, Is there any update on this issue 🤔 ?
Actually I am also facing the similar issue with my visual regression tests. I am getting different failure results while running VR tests on my local (MacOs with M1 chip) vs in CI (CircleCi).

We are using below node version -
Node: `v14.19.0`
NPM: `v6.14.16`
loki: `v0.30.3`

We are using `ubuntu-2004:202201-02` machine to run VR tests in CI.

**Comment by freshollie** [comment]
Ah I'm also using an M1, so maybe it's an ARM64 vs AMD64 thing?

**Comment by Manishy-97** [comment]
Yeah exactly you are correct seems like with the `AMD64` we are getting the same result as pipeline but getting different results with `ARM64`

**Comment by freshollie** [comment]
I wonder if a solution is to allow for [`--platform`](https://docs.docker.com/engine/reference/commandline/run/) to be passed? Maybe this is already possible

**Comment by freshollie** [comment]
@Manishy-97 I may try using `DOCKER_DEFAULT_PLATFORM` when running image snapshots `https://stackoverflow.com/a/66900911/1741602`

**Comment by Manishy-97** [comment]
Hey @freshollie , Thanks for the suggestion. Seems like docker platform is not getting updated even after setting up the `DOCKER_DEFAULT_PLATFORM` 🤔 

<img width="599" alt="image" src="https://user-images.githubusercontent.com/79149194/223463603-7b851e3a-a872-40f2-b98d-f2fa44252a9f.png">

**Comment by freshollie** [comment]
The platform arg is used when running docker images, running docker version indicates you system arch

**Comment by Manishy-97** [comment]
Oh yes I see that. I am facing a different issue with the `loki` tests after setting `DOCKER_DEFAULT_PLATFORM` to `linux/amd64` 
<img width="586" alt="image" src="https://user-images.githubusercontent.com/79149194/223980932-be53615f-a7e9-41b7-9d28-00eab0fd7ba9.png">

**Comment by rotemee** [comment]
Hey guys, any update?

Getting the same error..

**Comment by drauf** [comment]
Updating the docker image used by loki helped in my case.

Basically after adding `--chromeDockerImage 'yukinying/chrome-headless-browser-stable:114.0.5735.106'` to the command I get equal images on my M1 macbook and in CI running on some `amd64` machines.

**Comment by PeterChen1997** [comment]
sry.. I still got the issue

**Comment by Anxhul10** [comment]
for me this worked https://github.com/oblador/loki/issues/504#issuecomment-3168684251
