### ISSUE TITLE
Cannot call extract() unless you call cacheAllCSFFiles() first

### ISSUE THREAD

**Issue by p3k** [oblador/loki#436]
I am getting this error when I run `loki test` with the [storyStoreV7 feature](https://storybook.js.org/docs/react/configure/overview#on-demand-story-loading) being enabled in the Storybook configuration.

There is a corresponding issue in Storybook’s issue tracker: https://github.com/nuxt-community/storybook/issues/374

It seems to need a fix in application code, e.g. https://github.com/reg-viz/storycap/issues/594

**Comment by AleksRap** [comment]
Hi. I have the same problem. I tried to run loki using docker with image yukinying/chrome-headless-browser:90.0.4408.0

**Comment by AleksRap** [comment]
I solved this problem like this:

Go to the @loki/browser library. Find a file get-stories.js . You need to make the getStories function async and add a line `await window.__STORYBOOK_CLIENT_API__.storyStore.cache all CSV files();` before returning

But my tests failed with error  "Timeout after 10000ms"

**Comment by trunneml** [comment]
@AleksRap thanks your changes worked for me

**Comment by pavmax** [comment]
Had the same issue, fixed with @AleksRap changes.
I think these changes should be integrated in the library.

**Comment by HoneyQumo** [comment]
@AleksRap you are the best, it helped me a lot!

**Comment by HoneyQumo** [comment]
@AleksRap How can this be used for CI?

**Comment by ArthurGoupil** [comment]
Setting
```
  features: {
    storyStoreV7: false,
  }
```
in Storybook `main.js`
and `"chromeSelector": "#storybook-root > *",` in Loki config fixed everything for me, thanks @AleksRap !

**Comment by oblador** [comment]
Fixed in 0.31.2 👍
