### ISSUE TITLE
Failed to fetch stories

### ISSUE THREAD

**Issue by dandoniev** [oblador/loki#440]
![image](https://user-images.githubusercontent.com/80757554/222247295-5a529fb6-4486-49b6-9654-b64697dd611f.png)

Here's a screenshot of an error I receive when try to run following command locally: 
` loki --requireReference --reactUri file:./storybook-static`

Storybook has been successfully built, storybook-static folder is not empty, docker is running.

"loki": "^0.31.0"

Configuration: 
![image](https://user-images.githubusercontent.com/80757554/222248737-4aca3126-becb-4868-9167-db40a55159ce.png)

OS: Windows 10

P. S.: Script for local run of loki tests works totally fine

**Comment by serlapteff** [comment]
Same issue when running locally
![image](https://user-images.githubusercontent.com/11692387/223100212-99471cf7-5d0e-4537-9bd7-2d70b8593c0a.png)

This is when run in Github Actions
![image](https://user-images.githubusercontent.com/11692387/223100690-33caf212-0da7-40d1-959a-35d21d804afb.png)

**Comment by albohlabs** [comment]
May some firewall/docker related problem. Could you pls try to reinstall docker...

**Comment by oblador** [comment]
Fixed in 0.32.0
