### ISSUE TITLE
Using unsafe HTTP verb GET to invoke /json/new

### ISSUE THREAD

**Issue by gidztech** [oblador/loki#442]
```
FAIL chrome.app/FETCH_STORIES: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.
```
It looks like a recent version of Chrome now prevents `GET` requests being made against `/json/new` to mitigate XSRF attacks. The [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface) has changed it to use `PUT` to resolve this.

See: https://github.com/cyrus-and/chrome-remote-interface/commit/58ce8a3ad541709ab3883bc379e4a1dad5acb997

Loki uses this library as a dependency, and we need to upgrade to v0.32.1 to have this fix.

**Comment by stefanteixeira** [comment]
@techeverri @oblador would it be possible to get a new release, please?

The workaround does not work with Yarn resolutions. Also tried installing Loki from the master commit, but it does not generate "loki" binary and there is no instructions on how to do so.

Thanks in advance! 🙇🏻‍♂️

**Comment by peteragarclover** [comment]
> The workaround does not work with Yarn resolutions.
@stefanteixeira The workaround is working for us. I used:
```json
  "resolutions": {
    "chrome-remote-interface": "0.32.1"
  }
```

**Comment by Leave-On** [comment]
> 

can you please explain where exactly do i need to put this override rule? i tried adding it both in package.json and package-lock.json files without any success.

**Comment by techeverri** [comment]
> can you please explain where exactly do i need to put this override rule? i tried adding it both in package.json and package-lock.json files without any success.

As @gidztech mentioned here https://github.com/oblador/loki/issues/442#issuecomment-1460082773 you can check the official npm docs on how to use `overrides`
- https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

**Comment by techeverri** [comment]
[0.31.1](https://github.com/oblador/loki/releases/tag/v0.31.1) is out
