### ISSUE TITLE
Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.

### ISSUE THREAD

**Issue by don-boldyrev** [oblador/loki#444]
UI testing with loki v0.31.0 and with target chrome.app not working with chrome version 111.0.5563. Get the error on screenshot
![image](https://user-images.githubusercontent.com/27578057/224268987-b82e8f4d-0757-4cae-9ac7-7e31ee7661b2.png)

**Comment by techeverri** [comment]
Fixed by https://github.com/oblador/loki/pull/443

**Comment by techeverri** [comment]
Note: the fix hasn't been released yet

**Comment by techeverri** [comment]
Use workaround described here 👇 while this gets released 
- https://github.com/oblador/loki/issues/442#issuecomment-1460082773

**Comment by techeverri** [comment]
[0.31.1](https://github.com/oblador/loki/releases/tag/v0.31.1) is out
