### ISSUE TITLE
Failed fetch stories after Chrome update.

### ISSUE THREAD

**Issue by HappyMarvin** [oblador/loki#445]
Hi. I am trying to run a "loki test" and getting this:
"Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb."
![image](https://user-images.githubusercontent.com/67018534/224325549-80fd411b-e1f0-4ef7-8bc7-770ffd211070.png)

Tests broke after chrome update. How can I fix this? 
OS: WIN10
Chrome: 111.0.5563
Code in chromium
https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/devtools_http_handler.cc;drc=bd27852621593a92e1d8410154a139fa87cc0ebc;l=626

**Comment by techeverri** [comment]
Fixed by https://github.com/oblador/loki/pull/443

**Comment by techeverri** [comment]
Try the workaround described here 👇 while this gets released 
- https://github.com/oblador/loki/issues/442#issuecomment-1460082773

**Comment by HappyMarvin** [comment]
> Try the workaround described here 👇 while this gets released
> 
> * [Using unsafe HTTP verb GET to invoke /json/new #442 (comment)](https://github.com/oblador/loki/issues/442#issuecomment-1460082773)


We are using node+npm 6.14. And we can't update it now. "Overrides" not working(

**Comment by styriandev** [comment]
> Try the workaround described here 👇 while this gets released
> 
> * [Using unsafe HTTP verb GET to invoke /json/new #442 (comment)](https://github.com/oblador/loki/issues/442#issuecomment-1460082773)

Thanks for the workaround, worked for us using Node 18 and NPM 9.5.0

**Comment by davebrewer** [comment]
Have same issue as HappyMarvin w. being locked to low npm v and don't have access to npm override.
Any idea on when this fix might get merged?

**Comment by oblador** [comment]
[0.31.1](https://github.com/oblador/loki/releases/tag/v0.31.1) is out
