### ISSUE TITLE
Latest version of @ferocia-oss/osnap dependency broken

### ISSUE THREAD

**Issue by csmalin** [oblador/loki#447]
1.3.1 of @ferocia-oss/osnap is missing the src directory and causes loki to break. 

Was able to work around it for now by adding `"@ferocia-oss/osnap": "1.3.0",` to the resolutions key in my package.json

https://github.com/ferocia/osnap

**Comment by levibuzolic** [comment]
Sorry about that, should be fixed now in `1.3.2` - raising this issue on https://github.com/ferocia/osnap would have had this fixed sooner.

**Comment by levibuzolic** [comment]
@csmalin sorry, spoke too soon. This is now fixed in `@ferocia-oss/osnap@1.3.5` 🤦‍♂️

**Comment by csmalin** [comment]
Yeah, should have opened an issue there as well. Just wanted to make sure there was something here so if others could benefit from the workaround for the time being.
