### ISSUE TITLE
Issue with osnap when using pnpm

### ISSUE THREAD

**Issue by pfongkye** [oblador/loki#448]
Hello, I recently upgraded to latest version of loki (0.28.1 -> 0.31.1) but I am having some issues when installing and running with pnpm: 
```
> loki

(node:59566) UnhandledPromiseRejectionWarning: Error: Cannot find module '@ferocia-oss/osnap/src/ios'
Require stack:
- loki/examples/react/node_modules/.pnpm/@loki+target-native-ios-simulator@0.31.0/node_modules/@loki/target-native-ios-simulator/src/create-ios-simulator-target.js
...
```
The dependency is missing the `src` folder
![image](https://user-images.githubusercontent.com/1062699/227601367-f747a850-c552-4cc1-b9c8-e87bfc8b0d12.png)

When I ran with yarn, I don't have the same issue. I have the following
![image](https://user-images.githubusercontent.com/1062699/227601898-5ea3af3d-613e-4510-ad24-a702f675843b.png)

I think it is an issue with [osnap](https://github.com/ferocia/osnap) but I could not file an issue on the GitHub project itself.

FYI, I'm using pnpm 7.30.0

Regards,
Pascal.

**Comment by pfongkye** [comment]
I don't know if it is because of these [following lines](https://github.com/ferocia/osnap/blob/main/package.json#L38) in the package.json of osnap but it caught my attention:
```
  "np": {
    "yarn": true,
    "branch": "main"
  },
```

**Comment by trunneml** [comment]
It looks like that the missing file is in `osnap` and not in `@ferocia-oss/osnap`

**Comment by levibuzolic** [comment]
This should be fixed by upgrading `@ferocia-oss/osnap` to `1.3.2`

**Comment by kungfutse** [comment]
pinning the @ferocia-oss/osnap to version 1.3.2 causes es module error when running loki

```
> loki test --requireReference --reactUri='file:./dist-storybook'

/path/to/node_modules/@ferocia-oss/osnap/src/ios.js:45
var execa_1 = require("execa");
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /path/to/node_modules/@ferocia-oss/osnap/node_modules/execa/index.js from /path/to/node_modules/@ferocia-oss/osnap/src/ios.js not supported.
Instead change the require of index.js in /path/to/node_modules/@ferocia-oss/osnap/src/ios.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/path/to/node_modules/@ferocia-oss/osnap/src/ios.js:45:15)
    at Object.<anonymous> (/path/to/node_modules/@loki/target-native-ios-simulator/src/create-ios-simulator-target.js:3:15)
    at Object.<anonymous> (/path/to/node_modules/@loki/target-native-ios-simulator/src/index.js:1:34)
    at Object.<anonymous> (/path/to/node_modules/@loki/runner/src/commands/test/run-tests.js:16:5)
    at Object.<anonymous> (/path/to/node_modules/@loki/runner/src/commands/test/index.js:11:18)
    at getExecutorForCommand (/path/to/node_modules/@loki/runner/src/cli.js:21:14)
    at run (/path/to/node_modules/@loki/runner/src/cli.js:36:20)
    at Object.<anonymous> (/path/to/node_modules/@loki/runner/bin/loki:3:22) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by levibuzolic** [comment]
@kungfutse sorry about that, this should be now properly sorted in `@ferocia-oss/osnap@1.3.5`.

**Comment by pfongkye** [comment]
Hello, I tested it on my side and it seems to work now. Thank you all!
