### ISSUE TITLE
ES modules is not supported for ferocia-oss/osnap/node_modules/execa/index.js

### ISSUE THREAD

**Issue by d-otynshin** [oblador/loki#449]
After "npx loki test" -> @0.31.1

UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: PROJECT_PATH/@ferocia-oss/osnap/node_modules/execa/index.js

require() of ES modules is not supported.
require() of PROJECt_PATH/node_modules/@ferocia-oss/osnap/src/ios.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.

Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from PROJECT_PATH/node_modules/@ferocia-oss/osnap/node_modules/execa/package.json.

**Comment by levibuzolic** [comment]
Sorry about that, this should be now properly sorted in `@ferocia-oss/osnap@1.3.5`.
