### ISSUE TITLE
CI launch, problems with static files load

### ISSUE THREAD

**Issue by Aberkingaliev** [oblador/loki#460]
FAIL  chrome.app
       Fetching stories
       5 requests failed to load; file:///Users/usr/Desktop/dev_boilerplates/frontend/boilerplate-react/storybook
       -static/assets/iframe-ea5e55dd.js, file:///Users/usr/Desktop/dev_boilerplates/frontend/boilerplate-react/s
       torybook-static/sb-common-assets/nunito-sans-regular.woff2, file:///Users/usr/Desktop/dev_boilerplates/fro
       ntend/boilerplate-react/storybook-static/sb-common-assets/nunito-sans-italic.woff2, file:///Users/usr/Desk
       top/dev_boilerplates/frontend/boilerplate-react/storybook-static/sb-common-assets/nunito-sans-bold.woff2, 
       file:///Users/usr/Desktop/dev_boilerplates/frontend/boilerplate-react/storybook-static/sb-common-assets/nu
       nito-sans-bold-italic.woff2Some visual tests failed to run

**Comment by andreysharp** [comment]
The same issue
"storybook": "^7.0.18"
"loki": "^0.31.2",

**Comment by oblador** [comment]
Fixed in 0.32.0
