### ISSUE TITLE
Conflict peer-dependencies of latest Storybook 7 @7.0.21 when install latest loki@0.32.0

### ISSUE THREAD

**Issue by anatoly-ivashov** [oblador/loki#464]
When you install the latest version of storybook@7.0.21 and then install the latest version of loki@0.32.0, installing loki gives an error in peer-dependencies of @storybook/react. Storybook installing @storybook/react@^7, loki installing @storybook/react@^6.

![image](https://github.com/oblador/loki/assets/107929864/ef450441-6e1f-4a5f-a03b-ebb11965fccd)

**Comment by hamitovm** [comment]
I have the same problem with Storybook 7 @7.0.22. 
Helps yarn add loki --dev, but it doesn't work in github actions.
![image](https://github.com/oblador/loki/assets/79064353/b022b49b-d580-447c-897b-d3ca0c686454)

**Comment by ahsan-rao** [comment]
I am also facing the same issue when trying to install the latest loki and storybook. Any one find a solution to this yet?

**Comment by GRusla-n** [comment]
I add over overrides to package.json:
`"overrides": {
      "loki": {
      "@storybook/react": "[$@storybook/react](https://npmjs.com/package/@storybook/react)"
    }
 }   
`

**Comment by Greed2kk** [comment]
> "overrides": { "loki": { "@storybook/react": "$@storybook/react" } }

nice!

**Comment by ValeraKaktotak** [comment]
> For me works add overrides to package.json: `"overrides": { "loki": { "@storybook/react": "$@storybook/react" } } `

ty man!

**Comment by JS-NinjaNN** [comment]
> For me works add overrides to package.json: `"overrides": { "loki": { "@storybook/react": "$@storybook/react" } } `

Works for me, thanks man!

**Comment by squidjam** [comment]
I don't think we should accept overrides as a solution when there is a pull request waiting to get approved that could solve this issue?
Could the repo owners please check and approve the following PR, please?
https://github.com/oblador/loki/pull/476

**Comment by aalexxandr** [comment]
> For me works add overrides to package.json: `"overrides": { "loki": { "@storybook/react": "$@storybook/react" } } `

it's work. Thanks!

**Comment by gidztech** [comment]
This should no longer be an issue now that https://github.com/oblador/loki/releases/tag/v0.33.0 is released

**Comment by qooban** [comment]
There's still peer dependency issue when installing `loki`:
```
npm install --save-dev loki

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @loki/integration-react@0.33.0
npm WARN Found: @storybook/react@7.5.2
npm WARN node_modules/@storybook/react
npm WARN   dev @storybook/react@"^7.5.2" from the root project
npm WARN   3 more (@storybook/preset-react-webpack, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional @storybook/react@"^5 || ^6" from @loki/integration-react@0.33.0
npm WARN node_modules/loki/node_modules/@loki/integration-react
npm WARN   @loki/integration-react@"^0.33.0" from loki@0.33.0
npm WARN   node_modules/loki
npm WARN 
npm WARN Conflicting peer dependency: @storybook/react@6.5.16
npm WARN node_modules/@storybook/react
npm WARN   peerOptional @storybook/react@"^5 || ^6" from @loki/integration-react@0.33.0
npm WARN   node_modules/loki/node_modules/@loki/integration-react
npm WARN     @loki/integration-react@"^0.33.0" from loki@0.33.0
npm WARN     node_modules/loki
```

Created https://github.com/oblador/loki/pull/491 hoping that it can fix it.

**Comment by gidztech** [comment]
> There's still peer dependency issue when installing `loki`:
> 
> ```
> npm install --save-dev loki
> 
> npm WARN ERESOLVE overriding peer dependency
> npm WARN While resolving: @loki/integration-react@0.33.0
> npm WARN Found: @storybook/react@7.5.2
> npm WARN node_modules/@storybook/react
> npm WARN   dev @storybook/react@"^7.5.2" from the root project
> npm WARN   3 more (@storybook/preset-react-webpack, ...)
> npm WARN 
> npm WARN Could not resolve dependency:
> npm WARN peerOptional @storybook/react@"^5 || ^6" from @loki/integration-react@0.33.0
> npm WARN node_modules/loki/node_modules/@loki/integration-react
> npm WARN   @loki/integration-react@"^0.33.0" from loki@0.33.0
> npm WARN   node_modules/loki
> npm WARN 
> npm WARN Conflicting peer dependency: @storybook/react@6.5.16
> npm WARN node_modules/@storybook/react
> npm WARN   peerOptional @storybook/react@"^5 || ^6" from @loki/integration-react@0.33.0
> npm WARN   node_modules/loki/node_modules/@loki/integration-react
> npm WARN     @loki/integration-react@"^0.33.0" from loki@0.33.0
> npm WARN     node_modules/loki
> ```
> 
> Created #491 hoping that it can fix it.

It looks like it was updated in on the main `loki` package (https://github.com/oblador/loki/blob/master/packages/loki/package.json#L57) but not in the `integration-react` one. This issue only comes through as a warning, whereas the original was an error that broke the build. It doesn't seem to break anything currently (at least for me), but updating the other package is a good idea.

**Comment by Cheglok** [comment]
"storybook": "^8.0.5", "loki": "^0.35.1",
Same problem npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @goulash/ds-su@4.0.28
npm ERR! Found: @storybook/test@8.0.8
npm ERR! node_modules/@storybook/test
npm ERR!   dev @storybook/test@"^8.0.5" from the root project
npm ERR!   @storybook/test@"8.0.8" from @storybook/addon-interactions@8.0.8
npm ERR!   node_modules/@storybook/addon-interactions
npm ERR!     dev @storybook/addon-interactions@"^8.0.5" from the root project
