### ISSUE TITLE
How can I run loki test against a specific file?

### ISSUE THREAD

**Issue by michaeljholmes** [oblador/loki#468]
Hi there,

Is there a way to run loki test against a specific file

E.g.
loki test ./src/pathToFile/story.stories.tsx 

Many thanks

**Comment by techeverri** [comment]
Try using `--storiesFilter`

🔗 https://loki.js.org/command-line-arguments.html#loki-test

**Comment by techeverri** [comment]
For questions, please use https://github.com/oblador/loki/discussions

**Comment by michaeljholmes** [comment]
Hi there, thanks for the quick response.

I have tried every way I can think of to use this flag and the file name and it doesn't work. If I specify the file name e.i, I have a file called TestStory.stories.tsx and I use --storiesFilters TestStory that works fine. But an actual path doesn't.  Should paths work? If so I think this is a bug.

Many thanks

**Comment by techeverri** [comment]
Have you tried using a regular expression to match the path?

**Comment by michaeljholmes** [comment]
I have tried but I've had to luck with that either. Do you know of any examples where path is used?
