### ISSUE TITLE
Stories being skipped

### ISSUE THREAD

**Issue by inakiabt** [oblador/loki#47]
My stories were being skipped:

![dec-14-2017 15-37-56](https://user-images.githubusercontent.com/606852/34008660-d5fa79ca-e0e4-11e7-93fc-f5cd346d7b1e.gif)

So, after trying several things, I found my story was using an internal utility I built that uses [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) and that import was causing the story to be skipped. If I remove `import Form from 'react-jsonschema-form';` and update the code it works:

![dec-14-2017 15-38-18](https://user-images.githubusercontent.com/606852/34008659-d5c060e6-e0e4-11e7-954c-79d00566223c.gif)

Also, is there a way to debug to know why stories are being skipped?

**Comment by inakiabt** [comment]
I don't think `react-jsonschema-form` is the issue here, could a dependency that it uses?

**Comment by pelotom** [comment]
My stories are all being skipped too, and I have no idea why. I'm not using `react-jsonschema-form` either directly or indirectly.

**Comment by oblador** [comment]
There's a new way of extracting stories as of [0.10.0](https://github.com/oblador/loki/releases/tag/v0.10.0). Can you make sure it still happens on that version?

**Comment by InakiAbete-Reflektion** [comment]
@oblador It works! Now all my stories are run. The only issue I see is the `npx loki test|update` log output: the stories tree is repedately logged in the terminal when it should be "updated", right?

**Comment by inakiabt** [comment]
@oblador It works! Now all my stories are run. The only issue I see is the npx loki test|update log output: the stories tree is repedately logged in the terminal when it should be "updated", right?

**Comment by inakiabt** [comment]
Awesome, I'll use `--verboseRender` 👍
Thanks!

**Comment by inakiabt** [comment]
I think we are good. Closing the issue.

**Comment by oblador** [comment]
Yay! 😄

**Comment by oblador** [comment]
Btw, you can use `"loki": { "verboseRender": true}` in your package.json too if you want it to be default.
