### ISSUE TITLE
How to view test screenshots results in github actions

### ISSUE THREAD

**Issue by mr-scrpt** [oblador/loki#470]
I'm trying to configure ci using github actions and the tests using storybook and loki don't pass, although locally they do, I see that it happens in components that use transliteration, but I'm not sure exactly. And since I don't have problems locally, I can't see what exactly the problem is, since the tests crash and I can't see screenshots of the components with errors. Is it possible to save the screenshots that loki takes so that I can see them after a failed commit?

**Comment by techeverri** [comment]
Since you're using GitHub Actions, you could store the workflow data (Loki results) as artifacts.

More info on "workflow artifacts" here:
  - https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts

**Comment by techeverri** [comment]
For questions, please use https://github.com/oblador/loki/discussions
