### ISSUE TITLE
Docker container doesn't stop

### ISSUE THREAD

**Issue by sr258** [oblador/loki#482]
I'm evaluating Loki and I'm having issues with the Docker container not stopping after running Loki commands like `npx loki update`.

What I'm seeing in the CLI is this:
```
npx loki update
loki update v0.32.0
(node:30292) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
 PASS  chrome.docker/chrome.laptop/Components/XXXX
..... my tests ....
 PASS  chrome.docker
```

It's then stuck forever in this state. If I run `docker ps` I can see that the container is still running:
```
CONTAINER ID   IMAGE                                                     COMMAND                  CREATED          STATUS          PORTS                                           NAMES
ced5692c5538   yukinying/chrome-headless-browser-stable:100.0.4896.127   "/usr/bin/dumb-init …"   4 minutes ago    Up 4 minutes    0.0.0.0:34320->34320/tcp, :::34320->34320/tcp   eloquent_maxwell
```

If I stop if with `docker stop eloquent_maxwell`, the CLI that is stuck at `PASS chrome.docker` accepts commands again.

I've checked in the docker logs of the container and there's nothing suspicious going on, just some warning form my components, but nothing that would suggest that it's stuck.

How can I fix this?

Versions:
- loki 0.32.0
- Node 20.8.0
- Docker version 20.10.24, build 297e128
- OS: Ubuntu 22.04

**Comment by ronnyandre** [comment]
Same issue here, has had this problem for years.
