### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by joevaugh4n** [oblador/loki#503]
Hey team! I’m reaching out from the core SB team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

We also have an addons channel in our Discord community, which we’d like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message me (@joevaugh4n) so that I can give you the addon creator role! If you’re already in the server, please just ping me and I’ll respond to you there.

Thanks for being a part of our addon community!

Joe

**Comment by wolfe111** [comment]
Is Storybook 8 supported? I've just upgraded storybook to v8 and loki is unable to fetch my stories. Not sure if it is my setup or a Loki issue.

**Comment by leobastiani** [comment]
I tried today doing a straightforward setup with no results
After downgrading storybook to v7, I could use loki

**Comment by squidjam** [comment]
> Is Storybook 8 supported? I've just upgraded storybook to v8 and loki is unable to fetch my stories. Not sure if it is my setup or a Loki issue.

Loki is not compatible yet with Storybook 8.

There's a way to achieve similar testing with jest-image-snapshot but you will need to write some options and you will not get the same update/approve differentiated workflows.

**Comment by DILLIR** [comment]
Have you implemented a storybook 8 support? Today, tried to use it, but it still has storybook ^7 as last compatible version.

**Comment by anti-pode** [comment]
Hello @oblador. would you mind looking at this PR #509? It fixes some warnings when installing 'loki' along with @storybook/react 8.
