### ISSUE TITLE
chrome.docker differences when running in CI compared to on MacOS

### ISSUE THREAD

**Issue by PeterChen1997** [oblador/loki#504]
I got the same issue like https://github.com/oblador/loki/issues/434

I running the tests on my m1 mac and arm runner, got the diffs below

![image](https://github.com/oblador/loki/assets/21072589/52e98170-ba6c-470d-89ac-5fd973e0354b)

and  the current is 
![chrome_laptop_Components_AutoSizeTextarea_Editable](https://github.com/oblador/loki/assets/21072589/af94f4b9-fcdf-481c-aff2-0c58c6daa59c)

reference is
![chrome_laptop_Components_AutoSizeTextarea_Editable](https://github.com/oblador/loki/assets/21072589/f3536819-13cb-4e1a-8a31-acaab0f30344)

**Comment by PeterChen1997** [comment]
I use the default config for loki

And I don't want to set the tolerance to check the component clearly 👀 Is there any method to fix this?

I test it on the resemblejs. The two image actually not the same in a slight diff

 
![image](https://github.com/oblador/loki/assets/21072589/86e03384-53c6-4ea0-b49f-e84ef7d0ed2c)

**Comment by sr258** [comment]
The same here. The issue seems to be that the Chrome container renders differently in ARM64 and x86 architectures.

**Comment by juanbecher** [comment]
@PeterChen1997 How did you managed to fix this?

**Comment by PeterChen1997** [comment]
> [@PeterChen1997](https://github.com/PeterChen1997) How did you managed to fix this?

It needs to be use the same runner for generate image and check the image 👀

**Comment by Anxhul10** [comment]
Hey ! initially I got the same problem but when I use chrome.docker locally and then on CI I used docker actions and in entry point I first change package.json  chrome.docker to chrome.app and ran CI . 
I no longer got inconsistent test on CI or local.
