### ISSUE TITLE
 Could not parse url argument "?"

### ISSUE THREAD

**Issue by amadt** [oblador/loki#51]
I'm getting this in my own app as well as when I run the example app. 

```
loki update v0.7.0
 ❯ Chrome (docker)
   ✔ Start
   ✖ Fetch list of stories
     → Could not parse url argument "?" to pushState against base URL "about:blank".
     Test chrome.laptop
     Stop
Could not parse url argument "?" to pushState against base URL "about:blank".
SecurityError: Could not parse url argument "?" to pushState against base URL "about:blank".
    at HistoryImpl._sharedPushAndReplaceState (/Users/athomson/sandbox/nova/luna/node_modules/jsdom/lib/jsdom/living/window/History-impl.js:73:15)
    at HistoryImpl.pushState (/Users/athomson/sandbox/nova/luna/node_modules/jsdom/lib/jsdom/living/window/History-impl.js:54:10)
    at History.pushState (/Users/athomson/sandbox/nova/luna/node_modules/jsdom/lib/jsdom/living/generated/History.js:89:21)
    at evalmachine.<anonymous>:65329:20
    at Object.dispatch (evalmachine.<anonymous>:50529:7)
    at ConfigApi._renderError (evalmachine.<anonymous>:63464:24)
    at render (evalmachine.<anonymous>:63483:19)
    at ConfigApi.configure (evalmachine.<anonymous>:63498:9)
    at Object.<anonymous> (evalmachine.<anonymous>:57457:22)
    at Object.<anonymous> (evalmachine.<anonymous>:57458:30)
```

Any ideas?

**Comment by oblador** [comment]
Hi, could you share the repo with me so I can investigate?

**Comment by oblador** [comment]
Or oh, it’s the example in this repo? 😄 Think it uses an outdated version of loki by default, let me update it.

**Comment by amadt** [comment]
Yep. I got it in the example repo as well.

**Comment by ericketts** [comment]
I created a fresh react project with `create-react-app`, made a simple button component, added storybook to the app with [`getstorybook`](https://github.com/storybooks/storybook#getting-started), added a story for that button component, and followed the [directions to configure loki](https://loki.js.org/getting-started.html); 

the result is the same error posted above.

**Comment by lizho-ling** [comment]
+1, with latest create-react-app, met this issue.

**Comment by RobbinHabermehl** [comment]
Unfortunately I'm experiencing this issue as well. It concerns a manually configured app, I both tried v0.8.0 and v0.9.0 of loki.

The configuration is very minimal:
```json
{
  "loki": {
    "configurations": {
      "chrome.laptop": {
        "target": "chrome.docker",
        "width": 1366,
        "height": 768
      }
    }
  }
}
```

The version of `@storybook/react` that's being used is 3.3.10.

**Comment by naomiHauret** [comment]
I'm having the same issue as well (tested v0.9.0 and 0.9.1 with @storybook/react 3.3.10) on a manually configured app. [Here's the repo](https://github.com/naomiHauret/frontkit-react-cerebral).

**Comment by luciano-jr** [comment]
Same problem here

**Comment by penx** [comment]
I get this issue on @storybook/react@3.2.18 and above, but not on 3.2.17 and below.

I would recommend downgrading to 3.2.17 for now.

@oblador can you add to the readme what versions of storybook this has been tested against? 

I was going to suggest adding the following to package.json:

```
peerDependencies {
  "@storybook/react": ">=3 <3.2.18"
}
```

...but I guess it's not just the react version of storybook that could be a peer dependency and don't think there's a way to say 'either or' in peerDependencies.

**Comment by ericketts** [comment]
@penx when you say "on @3.2.18 and above", you're referring to the `storybook` dependency, correct? 

I guess the question then is what changed between .17 and .18 that might have caused loki to break..

**Comment by penx** [comment]
yes exactly

**Comment by penx** [comment]
Ah this should work:

```
peerDependencies {
  "@storybook/ui": ">=3 <3.2.18"
}
```

**Comment by RobbinHabermehl** [comment]
Installing v3.2.17 of `@storybook/ui` doesn't resolve the issue in my case unfortunately.

**Comment by penx** [comment]
did you also downgrade the other storybook packages e.g. `@storybook/react`?

**Comment by RobbinHabermehl** [comment]
No, I didn't actually @penx. Doing so results in a whole lot of Babel related errors though..

@oblador, do you have any idea where I can find the origin of this issue? I'd like to assist on solving it and pointing me in the right direction will probably save a lot of time debugging.

**Comment by penx** [comment]
You could try looking at the differences between @storybook/ui@3.2.17 and @3.2.18 in git and see if there's anything that stands out, i.e. a difference in the url pattern for components

**Comment by RobbinHabermehl** [comment]
I can't discover any significant changes: https://github.com/storybooks/storybook/compare/v3.2.17…v3.2.18.

**Comment by skambo** [comment]
Any update on this issue? I am also experiencing the same issue when I try to run `loki update`

**Comment by nuc** [comment]
So, it seems that jsdom complains when the storybook first launches and it does a `history.replaceState` with only `?` as the query string:

https://github.com/storybooks/storybook/blob/850e48d39e6367c9dd077df21c8cbea11c840c1b/lib/core/src/client/preview/syncUrlWithStore.js#L24

I experimented by adding a condition to only do the `replaceState` if there is a query string, but then I got the error that no stories were found.

**Comment by ericketts** [comment]
@nuc have you tried `replaceState`ing with the empty string if there's no query string?

**Comment by nuc** [comment]
@ericketts Same, `Error: No stories were found.`

**Comment by nuc** [comment]
`@storybook/react@3.1.7` with `loki@0.9.1` works.

**Comment by RobbinHabermehl** [comment]
Using the latest versions of Storybook (3.4.0-x) still results in the `Could not parse url argument "?" to replaceState against base URL "about:blank".` error.

It seems like Loki just can't open the Storybook URL somehow. Even adding the right URL hardcoded to the source won't resolve it though. Any thoughts @oblador?

**Comment by x1c0** [comment]
+ 1 with the same issue. I'm trying with @storybook/angular and i managed to get it working locally until I got this error. If this will be fixed, I'm happy to add support for Angular 🤓

**Comment by nuc** [comment]
@oblador I'd happily spend some time to get loki up to speed with the latest versions of storybook.

I [experimented a bit](https://github.com/oblador/loki/issues/51#issuecomment-367347619) but I couldn't figure out how to test out my changes, without having to run `loki test` every time. 

Some guidance on how to setup a loki dev environment would be really useful.

Cheers!

**Comment by varya** [comment]
I have the same issue with various combinations of react, storybook and loki. For example, 

```
"@storybook/react": "^3.2.17",
"loki": "^0.8.0",
"react": "^15.6.0",
```

**Comment by felquis** [comment]
@nuc Are you still on? Let's try something different.

**Comment by felquis** [comment]
@nuc I found out the errors comes from this line https://github.com/oblador/loki/blob/3306f812b3f9984476f35bbad30e83506bd89948/src/targets/chrome/fetch-storybook-worker.js#L26 not sure 🤔 what is going on

**Comment by priomsrb** [comment]
This error seems to happen because storybook calls `window.history.replaceState()` while inside `about:blank`. This is because JSDOM sets the window location to `about:blank` by default. To fix this, I added the url argument to the JSDOM constructor [here](https://github.com/oblador/loki/blob/3306f812b3f9984476f35bbad30e83506bd89948/src/targets/chrome/get-browser-globals.js#L3):

```
function getBrowserGlobals(html, url) {
    const dom = new JSDOM(html, { url });
```

I also changed the following line [here](https://github.com/oblador/loki/blob/3306f812b3f9984476f35bbad30e83506bd89948/src/targets/chrome/fetch-storybook-worker.js#L10):

```
    const browser = getBrowserGlobals(html, baseUrl);
```

This lets me get past this error. However, I then end up with "No stories were found." as mentioned by others above.

**Comment by priomsrb** [comment]
As for the "No stories were found." error, it seems to be because loki is initialized before my stories are included. I managed to fix it by removing `import 'loki/configure-react';` at the top of my `.storybook/config.js` and instead requiring it at the end of `loadStories`:

```
function loadStories() {
  require('../stories/index.js');
  require('loki/configure-react');
}

configure(loadStories, module);
```

Now I'm getting errors because JSDOM is not compatible with some libraries that my stories use. Maybe there's another way of getting all stories without using JSDOM.

**Comment by daemonsy** [comment]
Hi, I'm facing the same issues. @priomsrb 's changes does the trick. Seems that there are two issues: 
1. jsdom issue with `about:blank` being its default page and `pushState` not working on it 
2. `configure-react`  has to run after stories are loaded by Storybook. Maybe in this case, the import shouldn't be a side effect? Should instead import a function that you can invoke after loading stories

**Comment by oblador** [comment]
Hey guys, could you try out [0.9.2](https://github.com/oblador/loki/releases/tag/v0.9.2) and see if it fixes it?
