### ISSUE TITLE
test passed but approve replaces images

### ISSUE THREAD

**Issue by jacksbox** [oblador/loki#69]
Recently loki started showing strange behaviour: 
`loki test` complete without an error, also the the `difference` folder is empty. But if I do `loki approve` afterwards, it suddenly changes files in the `reference` folder.
This also occurs if the tests fail, and I `approve` afterwards: All failed images get moved to `references` but also some other images suddenly get changed in the `reference` folder.

v.0.12.0 with following options: 
`--chromeRetries 3 --diffingEngine gm --requireReference --chromeTolerance 1.0 --chromeConcurrency 10 --verboseRenderer true --chromeDockerImage yukinying/chrome-headless:63.0.3230.2`

**Comment by nowells** [comment]
This is an issue with `gm` not working properly I believe. The images are definitely different, but `gm` somehow does not pick up on that (or the code in loki does not catch the error and swallows it, I haven't looked into it yet) But I saw this issue as well when I first tried out `gm` and decided to stick with `looks-same` until this is fixed. I certainly like the output of `gm` better from the docs, so I'll probably poke at it as well to see if I can find the issue.

**Comment by oblador** [comment]
There was a recent change in how loki handles `gm` errors: https://github.com/oblador/loki/pull/62 maybe that's a regression

**Comment by oblador** [comment]
I'm not sure that's something I can do much about besides having different default thresholds for gm and looks-same or even setting default threshold to 0. In my current project we use gm and tolerance of `0.01`. We started out with 0 but think there was some edge cases where it would then detect changes where there weren't any.

**Comment by nowells** [comment]
I feel like a threshold of `0` is a better default to avoid that case like the one I posted above where technically by percentage it is within threshold but clearly is a breaking change that would have been missed.

**Comment by jacksbox** [comment]
Having a lower threshold helped a lot. Thanks.

But there is still the point of approving and having images changed where the diff didn't raise an error.
I think a quick and easy solution would be, on `loki approve` not to copy over __all__ images from `current`, but just the ones witch matching names to the ones in 'difference' (which are all images where an error was raised)

**Comment by oblador** [comment]
I'm closing this for now with the default tolerance set to 0. Reopen or file a new issue if you think this is not enough.
