### ISSUE TITLE
Request failed to load

### ISSUE THREAD

**Issue by geraintf** [oblador/loki#80]
Hi,

I've been messing around with loki running locally and found it super easy to get up and running. 

I'm now looking to get it working as part of a CI pipeline. I am using the command found on your docs for starters (`build-storybook && loki --requireReference --reactUri file:./storybook-static`) but I'm getting an error that 1 request failed to load. The error messages don't really give me that much to go on, any suggestions/help would be greatly appreciated.

<img width="911" alt="screen shot 2018-07-12 at 12 03 21" src="https://user-images.githubusercontent.com/13432246/42629684-23e8d5a0-85cc-11e8-8a66-fd53c18b3fb1.png">

**Comment by oblador** [comment]
Hi, that's interesting. Seems there's a bug in the relative path resolver when using the app. It should be fixed, but you should really look into using docker if you want to use it in CI.

**Comment by geraintf** [comment]
@oblador Thanks for the fast reply and the fast fix! What are the benefits of using docker for CI over this approach?

**Comment by oblador** [comment]
It will make your tests more deterministic. If you dont use docker then the font rendering etc will depend on the OS, Chrome version and in some cases what monitor you are using.

**Comment by storm2513** [comment]
Still facing with same issue on CI using docker ☹️

**Comment by dandoniev** [comment]
Any updates on this?

**Comment by HoneyQumo** [comment]
Any updates on this?
