### ISSUE TITLE
Failed to fetch stories in CI

### ISSUE THREAD

**Issue by geraintf** [oblador/loki#85]
Hi,
I'm running the command as per docs to run loki in CI (gitlabs) - `build-storybook && loki --requireReference --reactUri file:./storybook-static`. It builds ok but when it trys to fetch stories it fails because the server is down - I didn't think we had to run storybook if we used static, is that correct or have I misunderstood?

![screen shot 2018-07-17 at 15 47 56](https://user-images.githubusercontent.com/13432246/42825578-36a09036-89da-11e8-8de0-bfe29d0d74b5.png)

**Comment by oblador** [comment]
Hi, looks like it should work; any chance I can have a look at your repo and setup?

**Comment by nowells** [comment]
I believe this is the issue with relative file paths which was recently solved but not released. Try `build-storybook && loki --requireReference --reactUri file:$PWD/storybook-static` (adding `$PWD` to the path)

**Comment by oblador** [comment]
@nowells: Your fix is in 0.12, maybe we need additional work here?

**Comment by techeverri** [comment]
Wasn't it your fix @oblador? 🤔 
Introduced by #81

I think it was not included in v0.12.0

**Comment by oblador** [comment]
That fix was only for Chrome app, docker was already working.

**Comment by geraintf** [comment]
@nowells Adding `$PWD` had the same result

@oblador I'll include as much info as I can below

Files structure:
```
- root
    -ci.yml
    -packages
        - ui-components
            - .loki
            - .storybook (custom config in here)
            - src (ui components in here)
            - stories
            - package.json
```      

  Package.json
```
{
    "engines": {
        "node": ">=8.4.0"
    },
    "scripts": {
        "vr:update": "yarn loki update",
        "vr:test": "yarn loki test",
        "vr:report": "cd .loki && reg-cli ./current/ ./reference/ ./reg-diff/ -R ./report.html -I && cp -r difference/ reg-diff && open ./report.html",
        "vr:ci-test": "build-storybook && loki --requireReference --reactUri file:./storybook-static"
    },
    "devDependencies": {
        "loki": "^0.12.0",
    },
    "loki": {
        "storiesFilter": "^(?:(?!(Spinner)|(Carousel)|(Scenes)).)*$",
        "configurations": {
            "chrome.laptop": {
                "target": "chrome.docker",
                "width": 1200,
                "height": 768
            },
            "chrome.iphone7": {
                "target": "chrome.docker",
                "preset": "iPhone 7"
            }
        }
    }
}
```

Ci build step
```
visual-regression-test:
  <<: *skip_on_tags
  image: docker-image
  stage: test
  script:
    - cd packages/ui-components
    - yarn vr:ci-test
```

Storybook config
```
import React from 'react';
import { configure, addDecorator } from '@storybook/react';
import 'loki/configure-react';
import { setOptions } from '@storybook/addon-options';
import { injectGlobal } from 'styled-components';

injectGlobal`
    ${globalStyles}
`;

addDecorator(story => ...);

const req = require.context('../stories', true, /.stories.js$/);

function loadStories() {
    req.keys().forEach(filename => req(filename));
}

configure(loadStories, module);

setOptions({
    url: ‘****',
    hierarchySeparator: /\//,
    showDownPanel: false,
});```

**Comment by oblador** [comment]
I'm gonna set up a test with Gitlab to reproduce the issue. Is this line supposed to have an actual docker image reference? `image: docker-image` If so, please provide it so I can reproduce your env.

**Comment by geraintf** [comment]
Thank you, unfortunately, it's an internal docker image so isn't accessible externally

**Comment by oblador** [comment]
OK, but can you provide the image that you base it on or set up a public repository that reproduces the issue? I'm shooting in the dark here :-)

**Comment by geraintf** [comment]
I appreciate that, let me see what I can do and get back to you

**Comment by oblador** [comment]
@geraintf Would you mind confirming that the solution proposed in https://github.com/oblador/loki/pull/90 works for you?

**Comment by geraintf** [comment]
@oblador That exact setup works exactly on a test project I've made (you get timeouts using 0.12 but I guess your PR fixes that) - I still get some issues running on my main project but that's just down to some internal images that are used and restrictions - I think I'll just have to work through them - but the original error seems to be fixed.

Thanks

**Comment by oblador** [comment]
@geraintf Please post about the other issues you're having so we can think about if we want to solve them on a framework level or not :-) In general I think that you should try to avoid externally hosted images as fixtures as it introduces flakiness in your tests, but it might also be useful to intercept those requests and serve placeholders instead.

**Comment by geraintf** [comment]
@oblador Sure, I'll post about the issues I come across. Want me to keep posting them as issues?

The project I'm working on uses an internal version of gitlabs which has it's own images, own npm registry etc for security reasons which I guess makes my implementation a little difficult

**Comment by oblador** [comment]
Yeah, let’s post as new issues, it’s hard to keep track of comments in closed ones
