### ISSUE TITLE
[Suggestion] loki update only unreferenced files

### ISSUE THREAD

**Issue by geraintf** [oblador/loki#95]
There is a scenario:

I have added a new story that has no reference files. At the same time as adding maybe unintentionally  regress another story, this would now fail `loki test`. 

Before running `loki test` I do `loki update` - this then adds the new reference for my new component but also replaces the old reference for the now broken component meaning I could accidentally introduce regression and not be aware of it.

Suggestion: Add a flag that I can pass into `loki update` that will only add references for those stories which currently have no reference images.

**Comment by oblador** [comment]
I’ll do you one better, add a reference file when there isn’t one when running `loki test`.

**Comment by geraintf** [comment]
Nice! Sounds good, how would that work with the requireReference flag? I guess it'd have to be either or?

**Comment by oblador** [comment]
On CI or with `requireReference` it would not update

**Comment by geraintf** [comment]
Yeah that's what I was thinking 👍

**Comment by oblador** [comment]
@geraintf Have a look at https://github.com/oblador/loki/pull/96

**Comment by geraintf** [comment]
@oblador Just had a play with it and it all seems to work fine. I just had a few thoughts:

- I think the docs should be updated to reflect the new behaviour.
- There's still the chance for someone to accidentally introduce regression by using update.
- The commands I now use for Loki are kinda unclear in terms of the process of how I use it. If I need to  add a new reference image I can run a test or update, but update will also modify existing references, update can also be used to approve changes to files as can the approve command. In my head it makes sense to have commands responsible for a single thing e.g. this is the command you use to add reference images, this is the command you use to test and this is the command you use to approve changes.

**Comment by geraintf** [comment]
@oblador I think your change helps (and removes a potential step from the users workflow). I still think there is a way that a user could unknowingly introduce regression.

- User adds a new story/component 
- User makes a change to some global styles (which breaks another component)
- User does `loki update` to add the new file (they _could_ just do `loki test` but not necessarily) 
- Loki adds the new reference images _and_ approves broken tests.

This leads to potential regression going into production.

**Comment by oblador** [comment]
IDK, this issue applies to jest snapshots too? Also you’d see these files both when committing and making a PR.

What is your proposed alternative workflow?

**Comment by geraintf** [comment]
Yeah, it's one of the downsides of jest, it relies on developers always looking through every failed snapshot (which might not always happen) but I guess the idea should be to make this as difficult as possible to happen.

I guess I imagine it being something like:
- Use `update` to add your initial ref images
- Make some changes and/or add new story
- Run `test`  
- Test fails because a) You have a story without a reference image b) A story with a reference image is different
- You run `update` - this adds any missing reference images (but `test` would still fail because of the differences)
- You then check that changes in reference images are what you expect, if so you `approve` 

At the moment that line between adding images and approving images is blurred with update also doing the job of approve.
